#ifndef MMT_TCPIP_PROTOCOLS
#define MMT_TCPIP_PROTOCOLS

#ifdef __cplusplus
extern "C" {
#endif

#include "mmt_contents_defs.h"
#include "mmt_tcpip_attributes.h"

#define MMT_SUPPORT_IPV6
#define PROTOCOL_HISTORY_SIZE 3

//#define PROTO_UNKNOWN 0 //Already defined in the core
//#define PROTO_META    1 //Already defined in the core
#define PROTO_163 2
#define PROTO_360 3
#define PROTO_302_FOUND 4
#define PROTO_JD 5
#define PROTO_56 6
#define PROTO_8021Q 7
#define PROTO_888POKER 8
#define PROTO_ABOUT 9
#define PROTO_ADCASH 10
#define PROTO_ADDTHIS 11
#define PROTO_ADF 12
#define PROTO_ADOBE 13
#define PROTO_AFP 14
#define PROTO_AH 15
#define PROTO_AIM 16
#define PROTO_AIMINI 17
#define PROTO_ALIBABA 18
#define PROTO_ALIPAY 19
#define PROTO_ALLEGRO 20
#define PROTO_AMAZON 21
#define PROTO_AMEBLO 22
#define PROTO_ANCESTRY 23
#define PROTO_ANGRYBIRDS 24
#define PROTO_ANSWERS 25
#define PROTO_AOL 26
#define PROTO_APPLE 27
#define PROTO_APPLEJUICE 28
#define PROTO_ARMAGETRON 29
#define PROTO_ARP 30
#define PROTO_ASK 31
#define PROTO_AVG 32
#define PROTO_AVI 33
#define PROTO_AWEBER 34
#define PROTO_AWS 35
#define PROTO_BABYLON 36
#define PROTO_BADOO 37
#define PROTO_BAIDU 38
#define PROTO_BANKOFAMERICA 39
#define PROTO_BARNESANDNOBLE 40
#define PROTO_BATMAN 41
#define PROTO_BATTLEFIELD 42
#define PROTO_BATTLENET 43
#define PROTO_BBB 44
#define PROTO_BBC_ONLINE 45
#define PROTO_BESTBUY 46
#define PROTO_BETFAIR 47
#define PROTO_BGP 48
#define PROTO_BIBLEGATEWAY 49
#define PROTO_BILD 50
#define PROTO_BING 51
#define PROTO_BITTORRENT 52
#define PROTO_BLEACHERREPORT 53
#define PROTO_BLOGFA 54
#define PROTO_BLOGGER 55
#define PROTO_BLOGSPOT 56
#define PROTO_BODYBUILDING 57
#define PROTO_BOOKING 58
#define PROTO_CBSSPORTS 59
#define PROTO_CNET 60
#define PROTO_CHANGE 61
#define PROTO_CHASE 62
#define PROTO_CHESS 63
#define PROTO_CHINAZ 64
#define PROTO_CITRIX 65
#define PROTO_CITRIXONLINE 66
#define PROTO_CLICKSOR 67
#define PROTO_CNN 68
#define PROTO_CNZZ 69
#define PROTO_COMCAST 70
#define PROTO_CONDUIT 71
#define PROTO_COPYSCAPE 72
#define PROTO_CORREIOS 73
#define PROTO_CRAIGSLIST 74
#define PROTO_CROSSFIRE 75
#define PROTO_DAILYMAIL 76
#define PROTO_DAILYMOTION 77
#define PROTO_DCERPC 78
#define PROTO_DIRECT_DOWNLOAD_LINK 79
#define PROTO_DEVIANTART 80
#define PROTO_DHCP 81
#define PROTO_DHCPV6 82
#define PROTO_DIGG 83
#define PROTO_DIRECTCONNECT 84
#define PROTO_DNS 85
#define PROTO_DOFUS 86
#define PROTO_DONANIMHABER 87
#define PROTO_DOUBAN 88
#define PROTO_DOUBLECLICK 89
#define PROTO_DROPBOX 90
#define PROTO_EBAY 91
#define PROTO_EDONKEY 92
#define PROTO_EGP 93
#define PROTO_EHOW 94
#define PROTO_EKSISOZLUK 95
#define PROTO_ELECTRONICSARTS 96
#define PROTO_ESP 97
#define PROTO_ESPN 98
#define PROTO_ETHERNET 99
#define PROTO_ETSY 100
#define PROTO_EUROPA 101
#define PROTO_EUROSPORT 102
#define PROTO_FACEBOOK 103
#define PROTO_FACETIME 104
#define PROTO_FASTTRACK 105
#define PROTO_FC2 106
#define PROTO_FEIDIAN 107
#define PROTO_FIESTA 108
#define PROTO_FILETOPIA 109
#define PROTO_FIVERR 110
#define PROTO_FLASH 111
#define PROTO_FLICKR 112
#define PROTO_FLORENSIA 113
#define PROTO_FOURSQUARE 114
#define PROTO_FOX 115
#define PROTO_FREE 116
#define PROTO_FTP 117
// #define PROTO_FTP_CONTROL 117	
#define PROTO_GADUGADU 118
#define PROTO_GAMEFAQS 119
#define PROTO_GAMESPOT 120
#define PROTO_GAP 121
#define PROTO_GARANTI 122
#define PROTO_GAZETEVATAN 123
#define PROTO_GIGAPETA 124
#define PROTO_GITHUB 125
#define PROTO_GITTIGIDIYOR 126
#define PROTO_GLOBO 127
#define PROTO_GMAIL 128
#define PROTO_GNUTELLA 129
#define PROTO_GOOGLE_MAPS 130
#define PROTO_GO 131
#define PROTO_GODADDY 132
#define PROTO_GOO 133
#define PROTO_GOOGLE 134
#define PROTO_GOOGLE_USER_CONTENT 135
#define PROTO_GOSMS 136
#define PROTO_GRE 137
#define PROTO_GROOVESHARK 138
#define PROTO_GROUPON 139
#define PROTO_GTALK 140
#define PROTO_GTP 141
#define PROTO_GTP2 142
#define PROTO_GUARDIAN 143
#define PROTO_GUILDWARS 144
#define PROTO_HABERTURK 145
#define PROTO_HAO123 146
#define PROTO_HEPSIBURADA 147
#define PROTO_HI5 148
#define PROTO_HALFLIFE2 149
#define PROTO_HOMEDEPOT 150
#define PROTO_HOOTSUITE 151
#define PROTO_HOTMAIL 152
#define PROTO_HTTP 153
#define PROTO_HTTP_CONNECT 154
#define PROTO_HTTP_PROXY 155
#define PROTO_HTTP_APPLICATION_ACTIVESYNC 156
#define PROTO_HUFFINGTONPOST 157
#define PROTO_HURRIYET 158
#define PROTO_I23V5 159
#define PROTO_IAX 160
#define PROTO_ICECAST 161
#define PROTO_APPLE_ICLOUD 162
#define PROTO_ICMP 163
#define PROTO_ICMPV6 164
#define PROTO_IFENG 165
#define PROTO_IGMP 166
#define PROTO_IGN 167
#define PROTO_IKEA 168
#define PROTO_IMAP 169
#define PROTO_IMAPS 170
#define PROTO_IMDB 171
#define PROTO_IMESH 172
#define PROTO_IMESSAGE 173
#define PROTO_IMGUR 174
#define PROTO_LEBONCOIN 175
#define PROTO_INDIATIMES 176
#define PROTO_INSTAGRAM 177
#define PROTO_IP 178
#define PROTO_IP_IN_IP 179
#define PROTO_IPP 180
#define PROTO_IPSEC 181
#define PROTO_IPV6 182
#define PROTO_IRC 183
#define PROTO_IRS 184
#define PROTO_APPLE_ITUNES 185
#define PROTO_UNENCRYPED_JABBER 186
#define PROTO_JAPANPOST 187
#define PROTO_KAKAO 188
#define PROTO_KAT 189
#define PROTO_ORANGEFR 190
#define PROTO_KERBEROS 191
#define PROTO_KING 192
#define PROTO_KOHLS 193
#define PROTO_KONGREGATE 194
#define PROTO_KONTIKI 195
#define PROTO_L2TP 196
#define PROTO_LASTFM 197
#define PROTO_LDAP 198
#define PROTO_LEAGUEOFLEGENDS 199
#define PROTO_LEGACY 200
#define PROTO_LETV 201
#define PROTO_LINKEDIN 202
#define PROTO_LIVE 203
#define PROTO_LIVEDOOR 204
#define PROTO_LIVEMAIL 205
#define PROTO_LIVEINTERNET 206
#define PROTO_LIVEJASMIN 207
#define PROTO_LIVEJOURNAL 208
#define PROTO_LIVESCORE 209
#define PROTO_LIVINGSOCIAL 210
#define PROTO_LOWES 211
#define PROTO_MACYS 212
#define PROTO_MAIL_RU 213
#define PROTO_MANET 214
#define PROTO_MANOLITO 215
#define PROTO_MAPLESTORY 216
#define PROTO_MATCH 217
#define PROTO_MDNS 218
#define PROTO_MEDIAFIRE 219
#define PROTO_MEEBO 220
#define PROTO_MGCP 221
#define PROTO_MICROSOFT 222
#define PROTO_MILLIYET 223
#define PROTO_MINECRAFT 224
#define PROTO_MINICLIP 225
#define PROTO_MLBASEBALL 226
#define PROTO_MMO_CHAMPION 227
#define PROTO_MMS 228
#define PROTO_MOVE 229
#define PROTO_MOZILLA 230
#define PROTO_MPEG 231
#define PROTO_MSN 232
#define PROTO_MSSQL 233
#define PROTO_MULTIPLY 234
#define PROTO_MYNET 235
#define PROTO_MYSPACE 236
#define PROTO_MYSQL 237
#define PROTO_MYWEBSEARCH 238
#define PROTO_NBA 239
#define PROTO_NEOBUX 240
#define PROTO_NETBIOS 241
#define PROTO_NETFLIX 242
#define PROTO_NETFLOW 243
#define PROTO_NEWEGG 244
#define PROTO_NEWSMAX 245
#define PROTO_NFL 246
#define PROTO_NFS 247
#define PROTO_NICOVIDEO 248
#define PROTO_NIH 249
#define PROTO_NORDSTROM 250
#define PROTO_NTP 251
#define PROTO_NYTIMES 252
#define PROTO_ODNOKLASSNIKI 253
#define PROTO_OFF 254
#define PROTO_OGG 255
#define PROTO_ONET 256
#define PROTO_OPENFT 257
#define PROTO_ORANGEDONKEY 258
#define PROTO_OSCAR 259
#define PROTO_OSPF 260
#define PROTO_OUTBRAIN 261
#define PROTO_OVERSTOCK 262
#define PROTO_PANDO 263
#define PROTO_PAYPAL 264
#define PROTO_PCANYWHERE 265
#define PROTO_PCH 266
#define PROTO_PCONLINE 267
#define PROTO_PHOTOBUCKET 268
#define PROTO_PINTEREST 269
#define PROTO_PLAYSTATION 270
#define PROTO_POGO 271
#define PROTO_POP 272
#define PROTO_POPS 273
#define PROTO_POPO 274
#define PROTO_PORNHUB 275
#define PROTO_POSTGRES 276
#define PROTO_PPLIVE 277
#define PROTO_PPP 278
#define PROTO_PPPOE 279
#define PROTO_PPSTREAM 280
#define PROTO_PPTP 281
#define PROTO_PREMIERLEAGUE 282
#define PROTO_QQ 283
#define PROTO_QQLIVE 284
#define PROTO_QUAKE 285
#define PROTO_QUICKTIME 286
#define PROTO_R10 287
#define PROTO_RADIUS 288
#define PROTO_RAKUTEN 289
#define PROTO_RDP 290
#define PROTO_REALMEDIA 291
#define PROTO_REDDIT 292
#define PROTO_REDTUBE 293
#define PROTO_REFERENCE 294
#define PROTO_RENREN 295
#define PROTO_ROBLOX 296
#define PROTO_ROVIO 297
#define PROTO_RTP 298
#define PROTO_RTSP 299
#define PROTO_SABAH 300
#define PROTO_SAHIBINDEN 301
#define PROTO_SALESFORCE 302
#define PROTO_SALON 303
#define PROTO_SCTP 304
#define PROTO_SEARCHNU 305
#define PROTO_SEARCH_RESULTS 306
#define PROTO_SEARS 307
#define PROTO_SECONDLIFE 308
#define PROTO_SECURESERVER 309
#define PROTO_SFLOW 310
#define PROTO_SHAZAM 311
#define PROTO_SHOUTCAST 312
#define PROTO_SINA 313
#define PROTO_SIP 314
#define PROTO_SITEADVISOR 315
#define PROTO_SKY 316
#define PROTO_SKYPE 317
#define PROTO_SKYROCK 318
#define PROTO_SKYSPORTS 319
#define PROTO_SLATE 320
#define PROTO_SLIDESHARE 321
#define PROTO_SMB 322
#define PROTO_SMTP 323
#define PROTO_SMTPS 324
#define PROTO_SNMP 325
#define PROTO_SOCRATES 326
#define PROTO_SOFTONIC 327
#define PROTO_SOGOU 328
#define PROTO_SOHU 329
#define PROTO_SOPCAST 330
#define PROTO_SOSO 331
#define PROTO_SOULSEEK 332
#define PROTO_SOUNDCLOUD 333
#define PROTO_SOURCEFORGE 334
#define PROTO_SPIEGEL 335
#define PROTO_SPORX 336
#define PROTO_SPOTIFY 337
#define PROTO_SQUIDOO 338
#define PROTO_SSDP 339
#define PROTO_SSH 340
#define PROTO_SSL 341
#define PROTO_STACK_OVERFLOW 342
#define PROTO_STATCOUNTER 343
#define PROTO_STEALTHNET 344
#define PROTO_STEAM 345
#define PROTO_STUMBLEUPON 346
#define PROTO_STUN 347
#define PROTO_SULEKHA 348
#define PROTO_SYSLOG 349
#define PROTO_TAGGED 350
#define PROTO_TAOBAO 351
#define PROTO_TARGET 352
#define PROTO_TCO 353
#define PROTO_TCP 354
#define PROTO_TDS 355
#define PROTO_TEAMVIEWER 356
#define PROTO_TELNET 357
#define PROTO_TFTP 358
#define PROTO_THEMEFOREST 359
#define PROTO_THE_PIRATE_BAY 360
#define PROTO_THUNDER 361
#define PROTO_TIANYA 362
#define PROTO_TLS 363
#define PROTO_TMALL 364
#define PROTO_TORRENTZ 365
#define PROTO_TRUPHONE 366
#define PROTO_TUBE8 367
#define PROTO_TUDOU 368
#define PROTO_TUENTI 369
#define PROTO_TUMBLR 370
#define PROTO_TVANTS 371
#define PROTO_TVUPLAYER 372
#define PROTO_TWITTER 373
#define PROTO_UBI 374
#define PROTO_UCOZ 375
#define PROTO_UDP 376
#define PROTO_UDPLITE 377
#define PROTO_UOL 378
#define PROTO_USDEPARTMENTOFSTATE 379
#define PROTO_USENET 380
#define PROTO_USTREAM 381
#define PROTO_HTTP_APPLICATION_VEOHTV 382
#define PROTO_VIADEO 383
#define PROTO_VIBER 384
#define PROTO_VIMEO 385
#define PROTO_VK 386
#define PROTO_VKONTAKTE 387
#define PROTO_VNC 388
#define PROTO_WALMART 389
#define PROTO_WARRIORFORUM 390
#define PROTO_WAYN 391
#define PROTO_WEATHER 392
#define PROTO_WEBEX 393
#define PROTO_WEEKLYSTANDARD 394
#define PROTO_WEIBO 395
#define PROTO_WELLSFARGO 396
#define PROTO_WHATSAPP 397
#define PROTO_WIGETMEDIA 398
#define PROTO_WIKIA 399
#define PROTO_WIKIMEDIA 400
#define PROTO_WIKIPEDIA 401
#define PROTO_WILLIAMHILL 402
#define PROTO_WINDOWSLIVE 403
#define PROTO_WINDOWSMEDIA 404
#define PROTO_WINMX 405
#define PROTO_WINUPDATE 406
#define PROTO_WORLD_OF_KUNG_FU 407
#define PROTO_WORDPRESS_ORG 408
#define PROTO_WARCRAFT3 409
#define PROTO_WORLDOFWARCRAFT 410
#define PROTO_WOWHEAD 411
#define PROTO_WWE 412
#define PROTO_XBOX 413
#define PROTO_XDMCP 414
#define PROTO_XHAMSTER 415
#define PROTO_XING 416
#define PROTO_XINHUANET 417
#define PROTO_XNXX 418
#define PROTO_XVIDEOS 419
#define PROTO_YAHOO 420
#define PROTO_YAHOOGAMES 421
#define PROTO_YAHOOMAIL 422
#define PROTO_YANDEX 423
#define PROTO_YELP 424
#define PROTO_YOUKU 425
#define PROTO_YOUPORN 426
#define PROTO_YOUTUBE 427
#define PROTO_ZAPPOS 428
#define PROTO_ZATTOO 429
#define PROTO_ZEDO 430
#define PROTO_ZOL 431
#define PROTO_ZYNGA 432
#define PROTO_3PC 433
#define PROTO_ANY_0HOP 434
#define PROTO_ANY_DFS 435
#define PROTO_ANY_HIP 436
#define PROTO_ANY_LOCAL 437
#define PROTO_ANY_PES 438
#define PROTO_ARGUS 439
#define PROTO_ARIS 440
#define PROTO_AX_25 441
#define PROTO_BBN_RCC_MON 442
#define PROTO_BNA 443
#define PROTO_BR_SAT_MON 444
#define PROTO_CBT 445
#define PROTO_CFTP 446
#define PROTO_CHAOS 447
#define PROTO_COMPAQ_PEER 448
#define PROTO_CPHB 449
#define PROTO_CPNX 450
#define PROTO_CRTP 451
#define PROTO_CRUDP 452
#define PROTO_DCCP 453
#define PROTO_DCN_MEAS 454
#define PROTO_DDP 455
#define PROTO_DDX 456
#define PROTO_DGP 457
#define PROTO_EIGRP 458
#define PROTO_EMCON 459
#define PROTO_ENCAP 460
#define PROTO_ETHERIP 461
#define PROTO_FC 462
#define PROTO_FIRE 463
#define PROTO_GGP 464
#define PROTO_GMTP 465
#define PROTO_HIP 466
#define PROTO_HMP 467
#define PROTO_I_NLSP 468
#define PROTO_IATP 469
#define PROTO_IDPR 470
#define PROTO_IDPR_CMTP 471
#define PROTO_IDRP 472
#define PROTO_IFMP 473
#define PROTO_IGP 474
#define PROTO_IL 475
#define PROTO_IPCOMP 476
#define PROTO_IPCV 477
#define PROTO_IPLT 478
#define PROTO_IPPC 479
#define PROTO_IPTM 480
#define PROTO_IPX_IN_IP 481
#define PROTO_IRTP 482
#define PROTO_IS_IS 483
#define PROTO_ISO_IP 484
#define PROTO_ISO_TP4 485
#define PROTO_KRYPTOLAN 486
#define PROTO_LARP 487
#define PROTO_LEAF_1 488
#define PROTO_LEAF_2 489
#define PROTO_MERIT_INP 490
#define PROTO_MFE_NSP 491
#define PROTO_MHRP 492
#define PROTO_MICP 493
#define PROTO_MOBILE 494
#define PROTO_MOBILITY_HEADER 495
#define PROTO_MPLS_IN_IP 496
#define PROTO_MTP 497
#define PROTO_MUX 498
#define PROTO_NARP 499
#define PROTO_NETBLT 500
#define PROTO_NSFNET_IGP 501
#define PROTO_NVP_II 502
#define PROTO_PGM 503
#define PROTO_PIM 504
#define PROTO_PIPE 505
#define PROTO_PNNI 506
#define PROTO_PRM 507
#define PROTO_PTP 508
#define PROTO_PUP 509
#define PROTO_PVP 510
#define PROTO_QNX 511
#define PROTO_RSVP 512
#define PROTO_RSVP_E2E_IGNORE 513
#define PROTO_RVD 514
#define PROTO_SAT_EXPAK 515
#define PROTO_SAT_MON 516
#define PROTO_SCC_SP 517
#define PROTO_SCPS 518
#define PROTO_SDRP 519
#define PROTO_SECURE_VMTP 520
#define PROTO_SHIM6 521
#define PROTO_SKIP 522
#define PROTO_SM 523
#define PROTO_SMP 524
#define PROTO_SNP 525
#define PROTO_SPRITE_RPC 526
#define PROTO_SPS 527
#define PROTO_SRP 528
#define PROTO_SSCOPMCE 529
#define PROTO_ST 530
#define PROTO_STP 531
#define PROTO_SUN_ND 532
#define PROTO_SWIPE 533
#define PROTO_TCF 534
#define PROTO_TLSP 535
#define PROTO_TP_PP 536
#define PROTO_TRUNK_1 537
#define PROTO_TRUNK_2 538
#define PROTO_UTI 539
#define PROTO_VINES 540
#define PROTO_VISA 541
#define PROTO_VMTP 542
#define PROTO_VRRP 543
#define PROTO_WB_EXPAK 544
#define PROTO_WB_MON 545
#define PROTO_WSN 546
#define PROTO_XNET 547
#define PROTO_XNS_IDP 548
#define PROTO_XTP 549
#define PROTO_BUZZNET 550
#define PROTO_COMEDY 551
#define PROTO_RAMBLER 552
#define PROTO_SMUGMUG 553
#define PROTO_ARCHIEVE 554
#define PROTO_CITYNEWS 555
#define PROTO_SCIENCESTAGE 556
#define PROTO_ONEWORLD 557
#define PROTO_DISQUS 558
#define PROTO_BLOGCU 559
#define PROTO_EKOLAY 560
#define PROTO_500PX 561
#define PROTO_FOTKI 562
#define PROTO_FOTOLOG 563
#define PROTO_JALBUM 564
#define PROTO_LEMONDE 565
#define PROTO_PANORAMIO 566
#define PROTO_SNAPFISH 567
#define PROTO_WEBSHOTS 568
#define PROTO_MEGA 569
#define PROTO_VIDOOSH 570
#define PROTO_AFREECA 571
#define PROTO_WILDSCREEN 572
#define PROTO_BLOGTV 573
#define PROTO_HULU 574
#define PROTO_MEVIO 575
#define PROTO_LIVESTREAM 576
#define PROTO_LIVELEAK 577
#define PROTO_DEEZER 578
#define PROTO_BLIPTV 579
#define PROTO_BREAK 580
#define PROTO_CITYTV 581
#define PROTO_COMEDYCENTRAL 582
#define PROTO_ENGAGEMEDIA 583
#define PROTO_SCREENJUNKIES 584
#define PROTO_RUTUBE 585
#define PROTO_SEVENLOAD 586
#define PROTO_MUBI 587
#define PROTO_IZLESENE 588
#define PROTO_VIDEO_HOSTING 589
#define PROTO_BOX 590
#define PROTO_SKYDRIVE 591
#define PROTO_7DIGITAL 592
#define PROTO_CLOUDFRONT 593
#define PROTO_TANGO 594
#define PROTO_WECHAT 595
#define PROTO_LINE 596
#define PROTO_BLOOMBERG 597
#define PROTO_MSCDN 598
#define PROTO_AKAMAI 599
#define PROTO_YAHOOMSG 600
#define PROTO_BITGRAVITY 601
#define PROTO_CACHEFLY 602
#define PROTO_CDN77 603
#define PROTO_CDNETWORKS 604
#define PROTO_CHINACACHE 605
#define PROTO_COTENDO 606
#define PROTO_EDGECAST 607
#define PROTO_FASTLY 608
#define PROTO_HIGHWINDS 609
#define PROTO_INTERNAP 610
#define PROTO_LEVEL3 611
#define PROTO_LIMELIGHT 612
#define PROTO_MAXCDN 613
#define PROTO_NETDNA 614
#define PROTO_VOXEL 615
#define PROTO_RACKSPACE 616
#define PROTO_GAMEFORGE 617
#define PROTO_METIN2 618
#define PROTO_OGAME 619
#define PROTO_BATTLEKNIGHT 620
#define PROTO_4STORY 621
#define PROTO_FBMSG 622 //Facebook messaging
#define PROTO_GCM 623 //Google Cloud Messaging
#define PROTO_SLL 624 //Linux Cooked Socket
#define PROTO_NDN 625 // NDN protocol
#define PROTO_NDN_HTTP 626 // NDN_HTTP protocol
#define PROTO_QUIC 627
#define PROTO_ORACLE 628
#define PROTO_REDIS 629	
#define PROTO_VMWARE 630
#define LAST_IMPLEMENTED_PROTOCOL PROTO_VMWARE

#define NB_SUPPORTED_PROTOCOLS (LAST_IMPLEMENTED_PROTOCOL + 1)

//#define PROTO_UNKNOWN_ALIAS "ukn" //Already defined in the core
//#define PROTO_META_ALIAS "META" //Already defined in the core
#define PROTO_163_ALIAS "163"
#define PROTO_360_ALIAS "360"
#define PROTO_302_FOUND_ALIAS "302_found"
#define PROTO_JD_ALIAS "jd"
#define PROTO_56_ALIAS "56"
#define PROTO_8021Q_ALIAS "8021q"
#define PROTO_888POKER_ALIAS "888poker"
#define PROTO_ABOUT_ALIAS "about"
#define PROTO_ADCASH_ALIAS "adcash"
#define PROTO_ADDTHIS_ALIAS "addthis"
#define PROTO_ADF_ALIAS "adf"
#define PROTO_ADOBE_ALIAS "adobe"
#define PROTO_AFP_ALIAS "afp"
#define PROTO_AH_ALIAS "ah"
#define PROTO_AIM_ALIAS "aim"
#define PROTO_AIMINI_ALIAS "aimini"
#define PROTO_ALIBABA_ALIAS "alibaba"
#define PROTO_ALIPAY_ALIAS "alipay"
#define PROTO_ALLEGRO_ALIAS "allegro"
#define PROTO_AMAZON_ALIAS "amazon"
#define PROTO_AMEBLO_ALIAS "ameblo"
#define PROTO_ANCESTRY_ALIAS "ancestry"
#define PROTO_ANGRYBIRDS_ALIAS "angrybirds"
#define PROTO_ANSWERS_ALIAS "answers"
#define PROTO_AOL_ALIAS "aol"
#define PROTO_APPLE_ALIAS "apple"
#define PROTO_APPLEJUICE_ALIAS "applejuice"
#define PROTO_ARMAGETRON_ALIAS "armagetron"
#define PROTO_ARP_ALIAS "arp"
#define PROTO_ASK_ALIAS "ask"
#define PROTO_AVG_ALIAS "avg"
#define PROTO_AVI_ALIAS "avi"
#define PROTO_AWEBER_ALIAS "aweber"
#define PROTO_AWS_ALIAS "aws"
#define PROTO_BABYLON_ALIAS "babylon"
#define PROTO_BADOO_ALIAS "badoo"
#define PROTO_BAIDU_ALIAS "baidu"
#define PROTO_BANKOFAMERICA_ALIAS "bankofamerica"
#define PROTO_BARNESANDNOBLE_ALIAS "barnesandnoble"
#define PROTO_BATMAN_ALIAS "batman"
#define PROTO_BATTLEFIELD_ALIAS "battlefield"
#define PROTO_BATTLENET_ALIAS "battlenet"
#define PROTO_BBB_ALIAS "bbb"
#define PROTO_BBC_ONLINE_ALIAS "bbc_online"
#define PROTO_BESTBUY_ALIAS "bestbuy"
#define PROTO_BETFAIR_ALIAS "betfair"
#define PROTO_BGP_ALIAS "bgp"
#define PROTO_BIBLEGATEWAY_ALIAS "biblegateway"
#define PROTO_BILD_ALIAS "bild"
#define PROTO_BING_ALIAS "bing"
#define PROTO_BITTORRENT_ALIAS "bittorrent"
#define PROTO_BLEACHERREPORT_ALIAS "bleacherreport"
#define PROTO_BLOGFA_ALIAS "blogfa"
#define PROTO_BLOGGER_ALIAS "blogger"
#define PROTO_BLOGSPOT_ALIAS "blogspot"
#define PROTO_BODYBUILDING_ALIAS "bodybuilding"
#define PROTO_BOOKING_ALIAS "booking"
#define PROTO_CBSSPORTS_ALIAS "cbssports"
#define PROTO_CNET_ALIAS "cnet"
#define PROTO_CHANGE_ALIAS "change"
#define PROTO_CHASE_ALIAS "chase"
#define PROTO_CHESS_ALIAS "chess"
#define PROTO_CHINAZ_ALIAS "chinaz"
#define PROTO_CITRIX_ALIAS "citrix"
#define PROTO_CITRIXONLINE_ALIAS "citrixonline"
#define PROTO_CLICKSOR_ALIAS "clicksor"
#define PROTO_CNN_ALIAS "cnn"
#define PROTO_CNZZ_ALIAS "cnzz"
#define PROTO_COMCAST_ALIAS "comcast"
#define PROTO_CONDUIT_ALIAS "conduit"
#define PROTO_COPYSCAPE_ALIAS "copyscape"
#define PROTO_CORREIOS_ALIAS "correios"
#define PROTO_CRAIGSLIST_ALIAS "craigslist"
#define PROTO_CROSSFIRE_ALIAS "crossfire"
#define PROTO_DAILYMAIL_ALIAS "dailymail"
#define PROTO_DAILYMOTION_ALIAS "dailymotion"
#define PROTO_DCERPC_ALIAS "dcerpc"
#define PROTO_DIRECT_DOWNLOAD_LINK_ALIAS "direct_download_link"
#define PROTO_DEVIANTART_ALIAS "deviantart"
#define PROTO_DHCP_ALIAS "dhcp"
#define PROTO_DHCPV6_ALIAS "dhcpv6"
#define PROTO_DIGG_ALIAS "digg"
#define PROTO_DIRECTCONNECT_ALIAS "directconnect"
#define PROTO_DNS_ALIAS "dns"
#define PROTO_DOFUS_ALIAS "dofus"
#define PROTO_DONANIMHABER_ALIAS "donanimhaber"
#define PROTO_DOUBAN_ALIAS "douban"
#define PROTO_DOUBLECLICK_ALIAS "doubleclick"
#define PROTO_DROPBOX_ALIAS "dropbox"
#define PROTO_EBAY_ALIAS "ebay"
#define PROTO_EDONKEY_ALIAS "edonkey"
#define PROTO_EGP_ALIAS "egp"
#define PROTO_EHOW_ALIAS "ehow"
#define PROTO_EKSISOZLUK_ALIAS "eksisozluk"
#define PROTO_ELECTRONICSARTS_ALIAS "electronicsarts"
#define PROTO_ESP_ALIAS "esp"
#define PROTO_ESPN_ALIAS "espn"
#define PROTO_ETHERNET_ALIAS "ethernet"
#define PROTO_ETSY_ALIAS "etsy"
#define PROTO_EUROPA_ALIAS "europa"
#define PROTO_EUROSPORT_ALIAS "eurosport"
#define PROTO_FACEBOOK_ALIAS "facebook"
#define PROTO_FACETIME_ALIAS "facetime"
#define PROTO_FASTTRACK_ALIAS "fasttrack"
#define PROTO_FC2_ALIAS "fc2"
#define PROTO_FEIDIAN_ALIAS "feidian"
#define PROTO_FIESTA_ALIAS "fiesta"
#define PROTO_FILETOPIA_ALIAS "filetopia"
#define PROTO_FIVERR_ALIAS "fiverr"
#define PROTO_FLASH_ALIAS "flash"
#define PROTO_FLICKR_ALIAS "flickr"
#define PROTO_FLORENSIA_ALIAS "florensia"
#define PROTO_FOURSQUARE_ALIAS "foursquare"
#define PROTO_FOX_ALIAS "fox"
#define PROTO_FREE_ALIAS "free"
#define PROTO_FTP_ALIAS "ftp"
#define PROTO_GADUGADU_ALIAS "gadugadu"
#define PROTO_GAMEFAQS_ALIAS "gamefaqs"
#define PROTO_GAMESPOT_ALIAS "gamespot"
#define PROTO_GAP_ALIAS "gap"
#define PROTO_GARANTI_ALIAS "garanti"
#define PROTO_GAZETEVATAN_ALIAS "gazetevatan"
#define PROTO_GIGAPETA_ALIAS "gigapeta"
#define PROTO_GITHUB_ALIAS "github"
#define PROTO_GITTIGIDIYOR_ALIAS "gittigidiyor"
#define PROTO_GLOBO_ALIAS "globo"
#define PROTO_GMAIL_ALIAS "gmail"
#define PROTO_GNUTELLA_ALIAS "gnutella"
#define PROTO_GOOGLE_MAPS_ALIAS "google_maps"
#define PROTO_GO_ALIAS "go"
#define PROTO_GODADDY_ALIAS "godaddy"
#define PROTO_GOO_ALIAS "goo"
#define PROTO_GOOGLE_ALIAS "google"
#define PROTO_GOOGLE_USER_CONTENT_ALIAS "google_user_content"
#define PROTO_GOSMS_ALIAS "gosms"
#define PROTO_GRE_ALIAS "gre"
#define PROTO_GROOVESHARK_ALIAS "groovesharks"
#define PROTO_GROUPON_ALIAS "groupon"
#define PROTO_GTALK_ALIAS "gtalk"
#define PROTO_GTP_ALIAS "gtp"
#define PROTO_GTP2_ALIAS "gtp2"
#define PROTO_GUARDIAN_ALIAS "guardian"
#define PROTO_GUILDWARS_ALIAS "guildwars"
#define PROTO_HABERTURK_ALIAS "haberturk"
#define PROTO_HAO123_ALIAS "hao123"
#define PROTO_HEPSIBURADA_ALIAS "hepsiburada"
#define PROTO_HI5_ALIAS "hi5"
#define PROTO_HALFLIFE2_ALIAS "halflife2"
#define PROTO_HOMEDEPOT_ALIAS "homedepot"
#define PROTO_HOOTSUITE_ALIAS "hootsuite"
#define PROTO_HOTMAIL_ALIAS "hotmail"
#define PROTO_HTTP_ALIAS "http"
#define PROTO_HTTP_CONNECT_ALIAS "http_connect"
#define PROTO_HTTP_PROXY_ALIAS "http_proxy"
#define PROTO_HTTP_APPLICATION_ACTIVESYNC_ALIAS "http_activesync"
#define PROTO_HUFFINGTONPOST_ALIAS "huffingtonpost"
#define PROTO_HURRIYET_ALIAS "hurriyet"
#define PROTO_I23V5_ALIAS "i23v5"
#define PROTO_IAX_ALIAS "iax"
#define PROTO_ICECAST_ALIAS "icecast"
#define PROTO_APPLE_ICLOUD_ALIAS "icloud"
#define PROTO_ICMP_ALIAS "icmp"
#define PROTO_ICMPV6_ALIAS "icmpv6"
#define PROTO_IFENG_ALIAS "ifeng"
#define PROTO_IGMP_ALIAS "igmp"
#define PROTO_IGN_ALIAS "ign"
#define PROTO_IKEA_ALIAS "ikea"
#define PROTO_IMAP_ALIAS "imap"
#define PROTO_IMAPS_ALIAS "imaps"
#define PROTO_IMDB_ALIAS "imdb"
#define PROTO_IMESH_ALIAS "imesh"
#define PROTO_IMESSAGE_ALIAS "imessage"
#define PROTO_IMGUR_ALIAS "imgur"
#define PROTO_LEBONCOIN_ALIAS "leboncoin"
#define PROTO_INDIATIMES_ALIAS "indiatimes"
#define PROTO_INSTAGRAM_ALIAS "instagram"
#define PROTO_IP_ALIAS "ip"
#define PROTO_IP_IN_IP_ALIAS "ip_in_ip"
#define PROTO_IPP_ALIAS "ipp"
#define PROTO_IPSEC_ALIAS "ipsec"
#define PROTO_IPV6_ALIAS "ipv6"
#define PROTO_IRC_ALIAS "irc"
#define PROTO_IRS_ALIAS "irs"
#define PROTO_APPLE_ITUNES_ALIAS "apple_itunes"
#define PROTO_UNENCRYPED_JABBER_ALIAS "jabber"
#define PROTO_JAPANPOST_ALIAS "japanpost"
#define PROTO_KAKAO_ALIAS "kakao"
#define PROTO_KAT_ALIAS "kat"
#define PROTO_ORANGEFR_ALIAS "orangefr"
#define PROTO_KERBEROS_ALIAS "kerberos"
#define PROTO_KING_ALIAS "king"
#define PROTO_KOHLS_ALIAS "kohls"
#define PROTO_KONGREGATE_ALIAS "kongregate"
#define PROTO_KONTIKI_ALIAS "kontiki"
#define PROTO_L2TP_ALIAS "l2tp"
#define PROTO_LASTFM_ALIAS "lastfm"
#define PROTO_LDAP_ALIAS "ldap"
#define PROTO_LEAGUEOFLEGENDS_ALIAS "leagueoflegends"
#define PROTO_LEGACY_ALIAS "legacy"
#define PROTO_LETV_ALIAS "letv"
#define PROTO_LINKEDIN_ALIAS "linkedin"
#define PROTO_LIVE_ALIAS "live"
#define PROTO_LIVEDOOR_ALIAS "livedoor"
#define PROTO_LIVEMAIL_ALIAS "livemail"
#define PROTO_LIVEINTERNET_ALIAS "liveinternet"
#define PROTO_LIVEJASMIN_ALIAS "livejasmin"
#define PROTO_LIVEJOURNAL_ALIAS "livejournal"
#define PROTO_LIVESCORE_ALIAS "livescore"
#define PROTO_LIVINGSOCIAL_ALIAS "livingsocial"
#define PROTO_LOWES_ALIAS "lowes"
#define PROTO_MACYS_ALIAS "macys"
#define PROTO_MAIL_RU_ALIAS "mail_ru"
#define PROTO_MANET_ALIAS "manet"
#define PROTO_MANOLITO_ALIAS "manolito"
#define PROTO_MAPLESTORY_ALIAS "maplestory"
#define PROTO_MATCH_ALIAS "match"
#define PROTO_MDNS_ALIAS "mdns"
#define PROTO_MEDIAFIRE_ALIAS "mediafire"
#define PROTO_MEEBO_ALIAS "meebo"
#define PROTO_MGCP_ALIAS "mgcp"
#define PROTO_MICROSOFT_ALIAS "microsoft"
#define PROTO_MILLIYET_ALIAS "milliyet"
#define PROTO_MINECRAFT_ALIAS "minecraft"
#define PROTO_MINICLIP_ALIAS "miniclip"
#define PROTO_MLBASEBALL_ALIAS "mlbaseball"
#define PROTO_MMO_CHAMPION_ALIAS "mmo_champion"
#define PROTO_MMS_ALIAS "mms"
#define PROTO_MOVE_ALIAS "move"
#define PROTO_MOZILLA_ALIAS "mozilla"
#define PROTO_MPEG_ALIAS "mpeg"
#define PROTO_MSN_ALIAS "msn"
#define PROTO_MSSQL_ALIAS "mssql"
#define PROTO_MULTIPLY_ALIAS "multiply"
#define PROTO_MYNET_ALIAS "mynet"
#define PROTO_MYSPACE_ALIAS "myspace"
#define PROTO_MYSQL_ALIAS "mysql"
#define PROTO_MYWEBSEARCH_ALIAS "mywebsearch"
#define PROTO_NBA_ALIAS "nba"
#define PROTO_NEOBUX_ALIAS "neobux"
#define PROTO_NETBIOS_ALIAS "netbios"
#define PROTO_NETFLIX_ALIAS "netflix"
#define PROTO_NETFLOW_ALIAS "netflow"
#define PROTO_NEWEGG_ALIAS "newegg"
#define PROTO_NEWSMAX_ALIAS "newsmax"
#define PROTO_NFL_ALIAS "nfl"
#define PROTO_NFS_ALIAS "nfs"
#define PROTO_NICOVIDEO_ALIAS "nicovideo"
#define PROTO_NIH_ALIAS "nih"
#define PROTO_NORDSTROM_ALIAS "nordstrom"
#define PROTO_NTP_ALIAS "ntp"
#define PROTO_NYTIMES_ALIAS "nytimes"
#define PROTO_ODNOKLASSNIKI_ALIAS "odnoklassniki"
#define PROTO_OFF_ALIAS "off"
#define PROTO_OGG_ALIAS "ogg"
#define PROTO_ONET_ALIAS "onet"
#define PROTO_OPENFT_ALIAS "openft"
#define PROTO_ORANGEDONKEY_ALIAS "orangedonkey"
#define PROTO_OSCAR_ALIAS "oscar"
#define PROTO_OSPF_ALIAS "ospf"
#define PROTO_OUTBRAIN_ALIAS "outbrain"
#define PROTO_OVERSTOCK_ALIAS "overstock"
#define PROTO_PANDO_ALIAS "pando"
#define PROTO_PAYPAL_ALIAS "paypal"
#define PROTO_PCANYWHERE_ALIAS "pcanywhere"
#define PROTO_PCH_ALIAS "pch"
#define PROTO_PCONLINE_ALIAS "pconline"
#define PROTO_PHOTOBUCKET_ALIAS "photobucket"
#define PROTO_PINTEREST_ALIAS "pinterest"
#define PROTO_PLAYSTATION_ALIAS "playstation"
#define PROTO_POGO_ALIAS "pogo"
#define PROTO_POP_ALIAS "pop"
#define PROTO_POPS_ALIAS "pops"
#define PROTO_POPO_ALIAS "popo"
#define PROTO_PORNHUB_ALIAS "pornhub"
#define PROTO_POSTGRES_ALIAS "postgres"
#define PROTO_PPLIVE_ALIAS "pplive"
#define PROTO_PPP_ALIAS "ppp"
#define PROTO_PPPOE_ALIAS "pppoe"
#define PROTO_PPSTREAM_ALIAS "ppstream"
#define PROTO_PPTP_ALIAS "pptp"
#define PROTO_PREMIERLEAGUE_ALIAS "premierleague"
#define PROTO_QQ_ALIAS "qq"
#define PROTO_QQLIVE_ALIAS "qqlive"
#define PROTO_QUAKE_ALIAS "quake"
#define PROTO_QUICKTIME_ALIAS "quicktime"
#define PROTO_R10_ALIAS "r10"
#define PROTO_RADIUS_ALIAS "radius"
#define PROTO_RAKUTEN_ALIAS "rakuten"
#define PROTO_RDP_ALIAS "rdp"
#define PROTO_REALMEDIA_ALIAS "realmedia"
#define PROTO_REDDIT_ALIAS "reddit"
#define PROTO_REDTUBE_ALIAS "redtube"
#define PROTO_REFERENCE_ALIAS "reference"
#define PROTO_RENREN_ALIAS "renren"
#define PROTO_ROBLOX_ALIAS "roblox"
#define PROTO_ROVIO_ALIAS "rovio"
#define PROTO_RTP_ALIAS "rtp"
#define PROTO_RTSP_ALIAS "rtsp"
#define PROTO_SABAH_ALIAS "sabah"
#define PROTO_SAHIBINDEN_ALIAS "sahibinden"
#define PROTO_SALESFORCE_ALIAS "salesforce"
#define PROTO_SALON_ALIAS "salon"
#define PROTO_SCTP_ALIAS "sctp"
#define PROTO_SEARCHNU_ALIAS "searchnu"
#define PROTO_SEARCH_RESULTS_ALIAS "search_results"
#define PROTO_SEARS_ALIAS "sears"
#define PROTO_SECONDLIFE_ALIAS "secondlife"
#define PROTO_SECURESERVER_ALIAS "secureserver"
#define PROTO_SFLOW_ALIAS "sflow"
#define PROTO_SHAZAM_ALIAS "shazam"
#define PROTO_SHOUTCAST_ALIAS "shoutcast"
#define PROTO_SINA_ALIAS "sina"
#define PROTO_SIP_ALIAS "sip"
#define PROTO_SITEADVISOR_ALIAS "siteadvisor"
#define PROTO_SKY_ALIAS "sky"
#define PROTO_SKYPE_ALIAS "skype"
#define PROTO_SKYROCK_ALIAS "skyrock"
#define PROTO_SKYSPORTS_ALIAS "skysports"
#define PROTO_SLATE_ALIAS "slate"
#define PROTO_SLIDESHARE_ALIAS "slideshare"
#define PROTO_SMB_ALIAS "smb"
#define PROTO_SMTP_ALIAS "smtp"
#define PROTO_SMTPS_ALIAS "smtps"
#define PROTO_SNMP_ALIAS "snmp"
#define PROTO_SOCRATES_ALIAS "socrates"
#define PROTO_SOFTONIC_ALIAS "softonic"
#define PROTO_SOGOU_ALIAS "sogou"
#define PROTO_SOHU_ALIAS "sohu"
#define PROTO_SOPCAST_ALIAS "sopcast"
#define PROTO_SOSO_ALIAS "soso"
#define PROTO_SOULSEEK_ALIAS "soulseek"
#define PROTO_SOUNDCLOUD_ALIAS "soundcloud"
#define PROTO_SOURCEFORGE_ALIAS "sourceforge"
#define PROTO_SPIEGEL_ALIAS "spiegel"
#define PROTO_SPORX_ALIAS "sporx"
#define PROTO_SPOTIFY_ALIAS "spotify"
#define PROTO_SQUIDOO_ALIAS "squidoo"
#define PROTO_SSDP_ALIAS "ssdp"
#define PROTO_SSH_ALIAS "ssh"
#define PROTO_SSL_ALIAS "ssl"
#define PROTO_STACK_OVERFLOW_ALIAS "stack_overflow"
#define PROTO_STATCOUNTER_ALIAS "statcounter"
#define PROTO_STEALTHNET_ALIAS "stealthnet"
#define PROTO_STEAM_ALIAS "steam"
#define PROTO_STUMBLEUPON_ALIAS "stumbleupon"
#define PROTO_STUN_ALIAS "stun"
#define PROTO_SULEKHA_ALIAS "sulekha"
#define PROTO_SYSLOG_ALIAS "syslog"
#define PROTO_TAGGED_ALIAS "tagged"
#define PROTO_TAOBAO_ALIAS "taobao"
#define PROTO_TARGET_ALIAS "target"
#define PROTO_TCO_ALIAS "tco"
#define PROTO_TCP_ALIAS "tcp"
#define PROTO_TDS_ALIAS "tds"
#define PROTO_TEAMVIEWER_ALIAS "teamviewer"
#define PROTO_TELNET_ALIAS "telnet"
#define PROTO_TFTP_ALIAS "tftp"
#define PROTO_THEMEFOREST_ALIAS "themeforest"
#define PROTO_THE_PIRATE_BAY_ALIAS "the_pirate_bay"
#define PROTO_THUNDER_ALIAS "thunder"
#define PROTO_TIANYA_ALIAS "tianya"
#define PROTO_TLS_ALIAS "tls"
#define PROTO_TMALL_ALIAS "tmall"
#define PROTO_TORRENTZ_ALIAS "torrentz"
#define PROTO_TRUPHONE_ALIAS "truphone"
#define PROTO_TUBE8_ALIAS "tube8"
#define PROTO_TUDOU_ALIAS "tudou"
#define PROTO_TUENTI_ALIAS "tuenti"
#define PROTO_TUMBLR_ALIAS "tumblr"
#define PROTO_TVANTS_ALIAS "tvants"
#define PROTO_TVUPLAYER_ALIAS "tvuplayer"
#define PROTO_TWITTER_ALIAS "twitter"
#define PROTO_UBI_ALIAS "ubi"
#define PROTO_UCOZ_ALIAS "ucoz"
#define PROTO_UDP_ALIAS "udp"
#define PROTO_UDPLITE_ALIAS "udplite"
#define PROTO_UOL_ALIAS "uol"
#define PROTO_USDEPARTMENTOFSTATE_ALIAS "usdepartmentofstate"
#define PROTO_USENET_ALIAS "usenet"
#define PROTO_USTREAM_ALIAS "ustream"
#define PROTO_HTTP_APPLICATION_VEOHTV_ALIAS "http_application_veohtv"
#define PROTO_VIADEO_ALIAS "viadeo"
#define PROTO_VIBER_ALIAS "viber"
#define PROTO_VIMEO_ALIAS "vimeo"
#define PROTO_VK_ALIAS "vk"
#define PROTO_VKONTAKTE_ALIAS "vkontakte"
#define PROTO_VNC_ALIAS "vnc"
#define PROTO_WALMART_ALIAS "walmart"
#define PROTO_WARRIORFORUM_ALIAS "warriorforum"
#define PROTO_WAYN_ALIAS "wayn"
#define PROTO_WEATHER_ALIAS "weather"
#define PROTO_WEBEX_ALIAS "webex"
#define PROTO_WEEKLYSTANDARD_ALIAS "weeklystandard"
#define PROTO_WEIBO_ALIAS "weibo"
#define PROTO_WELLSFARGO_ALIAS "wellsfargo"
#define PROTO_WHATSAPP_ALIAS "whatsapp"
#define PROTO_WIGETMEDIA_ALIAS "wigetmedia"
#define PROTO_WIKIA_ALIAS "wikia"
#define PROTO_WIKIMEDIA_ALIAS "wikimedia"
#define PROTO_WIKIPEDIA_ALIAS "wikipedia"
#define PROTO_WILLIAMHILL_ALIAS "williamhill"
#define PROTO_WINDOWSLIVE_ALIAS "windowslive"
#define PROTO_WINDOWSMEDIA_ALIAS "windowsmedia"
#define PROTO_WINMX_ALIAS "winmx"
#define PROTO_WINUPDATE_ALIAS "winupdate"
#define PROTO_WORLD_OF_KUNG_FU_ALIAS "world_of_kung_fu"
#define PROTO_WORDPRESS_ORG_ALIAS "wordpress_org"
#define PROTO_WARCRAFT3_ALIAS "warcraft3"
#define PROTO_WORLDOFWARCRAFT_ALIAS "worldofwarcraft"
#define PROTO_WOWHEAD_ALIAS "wowhead"
#define PROTO_WWE_ALIAS "wwe"
#define PROTO_XBOX_ALIAS "xbox"
#define PROTO_XDMCP_ALIAS "xdmcp"
#define PROTO_XHAMSTER_ALIAS "xhamster"
#define PROTO_XING_ALIAS "xing"
#define PROTO_XINHUANET_ALIAS "xinhuanet"
#define PROTO_XNXX_ALIAS "xnxx"
#define PROTO_XVIDEOS_ALIAS "xvideos"
#define PROTO_YAHOO_ALIAS "yahoo"
#define PROTO_YAHOOGAMES_ALIAS "yahoogames"
#define PROTO_YAHOOMAIL_ALIAS "yahoomail"
#define PROTO_YANDEX_ALIAS "yandex"
#define PROTO_YELP_ALIAS "yelp"
#define PROTO_YOUKU_ALIAS "youku"
#define PROTO_YOUPORN_ALIAS "youporn"
#define PROTO_YOUTUBE_ALIAS "youtube"
#define PROTO_ZAPPOS_ALIAS "zappos"
#define PROTO_ZATTOO_ALIAS "zattoo"
#define PROTO_ZEDO_ALIAS "zedo"
#define PROTO_ZOL_ALIAS "zol"
#define PROTO_ZYNGA_ALIAS "zynga"
#define PROTO_3PC_ALIAS "3pc"
#define PROTO_ANY_0HOP_ALIAS "any_0hop"
#define PROTO_ANY_DFS_ALIAS "any_dfs"
#define PROTO_ANY_HIP_ALIAS "any_hip"
#define PROTO_ANY_LOCAL_ALIAS "any_local"
#define PROTO_ANY_PES_ALIAS "any_pes"
#define PROTO_ARGUS_ALIAS "argus"
#define PROTO_ARIS_ALIAS "aris"
#define PROTO_AX_25_ALIAS "ax_25"
#define PROTO_BBN_RCC_MON_ALIAS "bbn_rcc_mon"
#define PROTO_BNA_ALIAS "bna"
#define PROTO_BR_SAT_MON_ALIAS "br_sat_mon"
#define PROTO_CBT_ALIAS "cbt"
#define PROTO_CFTP_ALIAS "cftp"
#define PROTO_CHAOS_ALIAS "chaos"
#define PROTO_COMPAQ_PEER_ALIAS "compaq_peer"
#define PROTO_CPHB_ALIAS "cphb"
#define PROTO_CPNX_ALIAS "cpnx"
#define PROTO_CRTP_ALIAS "crtp"
#define PROTO_CRUDP_ALIAS "crudp"
#define PROTO_DCCP_ALIAS "dccp"
#define PROTO_DCN_MEAS_ALIAS "dcn_meas"
#define PROTO_DDP_ALIAS "ddp"
#define PROTO_DDX_ALIAS "ddx"
#define PROTO_DGP_ALIAS "dgp"
#define PROTO_EIGRP_ALIAS "eigrp"
#define PROTO_EMCON_ALIAS "emcon"
#define PROTO_ENCAP_ALIAS "encap"
#define PROTO_ETHERIP_ALIAS "etherip"
#define PROTO_FC_ALIAS "fc"
#define PROTO_FIRE_ALIAS "fire"
#define PROTO_GGP_ALIAS "ggp"
#define PROTO_GMTP_ALIAS "gmtp"
#define PROTO_HIP_ALIAS "hip"
#define PROTO_HMP_ALIAS "hmp"
#define PROTO_I_NLSP_ALIAS "i_nlsp"
#define PROTO_IATP_ALIAS "iatp"
#define PROTO_IDPR_ALIAS "idpr"
#define PROTO_IDPR_CMTP_ALIAS "idpr_cmtp"
#define PROTO_IDRP_ALIAS "idrp"
#define PROTO_IFMP_ALIAS "ifmp"
#define PROTO_IGP_ALIAS "igp"
#define PROTO_IL_ALIAS "il"
#define PROTO_IPCOMP_ALIAS "ipcomp"
#define PROTO_IPCV_ALIAS "ipcv"
#define PROTO_IPLT_ALIAS "iplt"
#define PROTO_IPPC_ALIAS "ippc"
#define PROTO_IPTM_ALIAS "iptm"
#define PROTO_IPX_IN_IP_ALIAS "ipx_in_ip"
#define PROTO_IRTP_ALIAS "irtp"
#define PROTO_IS_IS_ALIAS "is_is"
#define PROTO_ISO_IP_ALIAS "iso_ip"
#define PROTO_ISO_TP4_ALIAS "iso_tp4"
#define PROTO_KRYPTOLAN_ALIAS "kryptolan"
#define PROTO_LARP_ALIAS "larp"
#define PROTO_LEAF_1_ALIAS "leaf_1"
#define PROTO_LEAF_2_ALIAS "leaf_2"
#define PROTO_MERIT_INP_ALIAS "merit_inp"
#define PROTO_MFE_NSP_ALIAS "mfe_nsp"
#define PROTO_MHRP_ALIAS "mhrp"
#define PROTO_MICP_ALIAS "micp"
#define PROTO_MOBILE_ALIAS "mobile"
#define PROTO_MOBILITY_HEADER_ALIAS "mobility_header"
#define PROTO_MPLS_IN_IP_ALIAS "mpls_in_ip"
#define PROTO_MTP_ALIAS "mtp"
#define PROTO_MUX_ALIAS "mux"
#define PROTO_NARP_ALIAS "narp"
#define PROTO_NETBLT_ALIAS "netblt"
#define PROTO_NSFNET_IGP_ALIAS "nsfnet_igp"
#define PROTO_NVP_II_ALIAS "nvp_ii"
#define PROTO_PGM_ALIAS "pgm"
#define PROTO_PIM_ALIAS "pim"
#define PROTO_PIPE_ALIAS "pipe"
#define PROTO_PNNI_ALIAS "pnni"
#define PROTO_PRM_ALIAS "prm"
#define PROTO_PTP_ALIAS "ptp"
#define PROTO_PUP_ALIAS "pup"
#define PROTO_PVP_ALIAS "pvp"
#define PROTO_QNX_ALIAS "qnx"
#define PROTO_RSVP_ALIAS "rsvp"
#define PROTO_RSVP_E2E_IGNORE_ALIAS "rsvp_e2e_ignore"
#define PROTO_RVD_ALIAS "rvd"
#define PROTO_SAT_EXPAK_ALIAS "sat_expak"
#define PROTO_SAT_MON_ALIAS "sat_mon"
#define PROTO_SCC_SP_ALIAS "scc_sp"
#define PROTO_SCPS_ALIAS "scps"
#define PROTO_SDRP_ALIAS "sdrp"
#define PROTO_SECURE_VMTP_ALIAS "secure_vmtp"
#define PROTO_SHIM6_ALIAS "shim6"
#define PROTO_SKIP_ALIAS "skip"
#define PROTO_SM_ALIAS "sm"
#define PROTO_SMP_ALIAS "smp"
#define PROTO_SNP_ALIAS "snp"
#define PROTO_SPRITE_RPC_ALIAS "sprite_rpc"
#define PROTO_SPS_ALIAS "sps"
#define PROTO_SRP_ALIAS "srp"
#define PROTO_SSCOPMCE_ALIAS "sscopmce"
#define PROTO_ST_ALIAS "st"
#define PROTO_STP_ALIAS "stp"
#define PROTO_SUN_ND_ALIAS "sun_nd"
#define PROTO_SWIPE_ALIAS "swipe"
#define PROTO_TCF_ALIAS "tcf"
#define PROTO_TLSP_ALIAS "tlsp"
#define PROTO_TP_PP_ALIAS "tp_pp"
#define PROTO_TRUNK_1_ALIAS "trunk_1"
#define PROTO_TRUNK_2_ALIAS "trunk_2"
#define PROTO_UTI_ALIAS "uti"
#define PROTO_VINES_ALIAS "vines"
#define PROTO_VISA_ALIAS "visa"
#define PROTO_VMTP_ALIAS "vmtp"
#define PROTO_VRRP_ALIAS "vrrp"
#define PROTO_WB_EXPAK_ALIAS "wb_expak"
#define PROTO_WB_MON_ALIAS "wb_mon"
#define PROTO_WSN_ALIAS "wsn"
#define PROTO_XNET_ALIAS "xnet"
#define PROTO_XNS_IDP_ALIAS "xns_idp"
#define PROTO_XTP_ALIAS "xtp"
#define PROTO_BUZZNET_ALIAS "buzznet"
#define PROTO_COMEDY_ALIAS "comedy"
#define PROTO_RAMBLER_ALIAS "rambler"
#define PROTO_SMUGMUG_ALIAS "smugmug"
#define PROTO_ARCHIEVE_ALIAS "archieve"
#define PROTO_CITYNEWS_ALIAS "citynews"
#define PROTO_SCIENCESTAGE_ALIAS "sciencestage"
#define PROTO_ONEWORLD_ALIAS "oneworld"
#define PROTO_DISQUS_ALIAS "disqus"
#define PROTO_BLOGCU_ALIAS "blogcu"
#define PROTO_EKOLAY_ALIAS "ekolay"
#define PROTO_500PX_ALIAS "500px"
#define PROTO_FOTKI_ALIAS "fotki"
#define PROTO_FOTOLOG_ALIAS "fotolog"
#define PROTO_JALBUM_ALIAS "jalbum"
#define PROTO_LEMONDE_ALIAS "lemonde"
#define PROTO_PANORAMIO_ALIAS "panoramio"
#define PROTO_SNAPFISH_ALIAS "snapfish"
#define PROTO_WEBSHOTS_ALIAS "webshots"
#define PROTO_MEGA_ALIAS "mega"
#define PROTO_VIDOOSH_ALIAS "vidoosh"
#define PROTO_AFREECA_ALIAS "afreeca"
#define PROTO_WILDSCREEN_ALIAS "wildscreen"
#define PROTO_BLOGTV_ALIAS "blogtv"
#define PROTO_HULU_ALIAS "hulu"
#define PROTO_MEVIO_ALIAS "mevio"
#define PROTO_LIVESTREAM_ALIAS "livestream"
#define PROTO_LIVELEAK_ALIAS "liveleak"
#define PROTO_DEEZER_ALIAS "deezer"
#define PROTO_BLIPTV_ALIAS "bliptv"
#define PROTO_BREAK_ALIAS "break"
#define PROTO_CITYTV_ALIAS "citytv"
#define PROTO_COMEDYCENTRAL_ALIAS "comedycentral"
#define PROTO_ENGAGEMEDIA_ALIAS "engagemedia"
#define PROTO_SCREENJUNKIES_ALIAS "screenjunkies"
#define PROTO_RUTUBE_ALIAS "rutube"
#define PROTO_SEVENLOAD_ALIAS "sevenload"
#define PROTO_MUBI_ALIAS "mubi"
#define PROTO_IZLESENE_ALIAS "izlesene"
#define PROTO_VIDEO_HOSTING_ALIAS "video_hosting"
#define PROTO_BOX_ALIAS "box"
#define PROTO_SKYDRIVE_ALIAS "skydrive"
#define PROTO_7DIGITAL_ALIAS "7digital"
#define PROTO_CLOUDFRONT_ALIAS "cloudfront"
#define PROTO_TANGO_ALIAS "tango"
#define PROTO_WECHAT_ALIAS "wechat"
#define PROTO_LINE_ALIAS "line"
#define PROTO_BLOOMBERG_ALIAS "bloomberg"
#define PROTO_MSCDN_ALIAS "mscdn"
#define PROTO_AKAMAI_ALIAS "akamai"
#define PROTO_YAHOOMSG_ALIAS "yahoomsg"
#define PROTO_BITGRAVITY_ALIAS "bitgravity"
#define PROTO_CACHEFLY_ALIAS "cachefly"
#define PROTO_CDN77_ALIAS "cdn77"
#define PROTO_CDNETWORKS_ALIAS "cdnetworks"
#define PROTO_CHINACACHE_ALIAS "chinacache"
#define PROTO_COTENDO_ALIAS "cotendo"
#define PROTO_EDGECAST_ALIAS "edgecast"
#define PROTO_FASTLY_ALIAS "fastly"
#define PROTO_HIGHWINDS_ALIAS "highwinds"
#define PROTO_INTERNAP_ALIAS "internap"
#define PROTO_LEVEL3_ALIAS "level3"
#define PROTO_LIMELIGHT_ALIAS "limelight"
#define PROTO_MAXCDN_ALIAS "maxcdn"
#define PROTO_NETDNA_ALIAS "netdna"
#define PROTO_VOXEL_ALIAS "voxel"
#define PROTO_RACKSPACE_ALIAS "rackspace"
#define PROTO_GAMEFORGE_ALIAS "gameforge"
#define PROTO_METIN2_ALIAS "metin2"
#define PROTO_OGAME_ALIAS "ogame"
#define PROTO_BATTLEKNIGHT_ALIAS "battleknight"
#define PROTO_4STORY_ALIAS "4story"
#define PROTO_FBMSG_ALIAS "fbmsg"
#define PROTO_GCM_ALIAS "gcm"
#define PROTO_SLL_ALIAS "sll"
#define PROTO_NDN_ALIAS "ndn"
#define PROTO_NDN_HTTP_ALIAS "ndn_http"	
#define PROTO_QUIC_ALIAS "quic"
#define PROTO_ORACLE_ALIAS "oracle"
#define PROTO_REDIS_ALIAS "redis"
#define PROTO_VMWARE_ALIAS "vmware"
// #define PROTO_FTP_CONTROL_ALIAS "ftp_control"
// #define PROTO_FTP_DATA_ALIAS "ftp_data"

#define PROTO_CLASS_UNKOWN         0
#define PROTO_CLASS_WEB            1
#define PROTO_CLASS_P2P            2
#define PROTO_CLASS_GAMING         3
#define PROTO_CLASS_STREAMING      4
#define PROTO_CLASS_CONVERSATIONAL 5
#define PROTO_CLASS_MAIL           6
#define PROTO_CLASS_FILETRANSFER   7
#define PROTO_CLASS_CLOUD_STORAGE  8
#define PROTO_CLASS_DDL            9
#define PROTO_CLASS_NETWORK       10
#define PROTO_CLASS_TUNNEL        11
#define PROTO_CLASS_DB            12
#define PROTO_CLASS_REMOTE        13
#define PROTO_CLASS_MISC          14
#define PROTO_CLASS_CDN           15

#define PROTO_CLASS_LABELS \
 "Unkown",                 \
 "Web",                    \
 "P2P",                    \
 "Gaming",                 \
 "Streaming",              \
 "Conversational",         \
 "Mail",                   \
 "FileTransfer",           \
 "CloudStorage",           \
 "DirectDownloadLink",     \
 "Network",                \
 "Tunnelling",             \
 "DataBase",               \
 "Remote",                 \
 "Misc",                   \
 "CDN"

#ifdef __cplusplus
}
#endif
#endif //MMT_TCPIP_PROTOCOLS
