/*
 * ocpp_data.h
 *
 *  Created on: Nov 20, 2024
 *      Author: vietpham
 */

/*
An example of a CSV file from VeriDevOps

TrolleyPos: 32.981, Hoistpos: 38.042, NoOfMarkers: 3, m1: (58901,70912) , m2: (72175,70950) , m3: (65803,71939) , m4: (46930,65566) , m5: (65795,72047) , m6: (70644,58001)
TrolleyPos: 32.978, Hoistpos: 38.124, NoOfMarkers: 3, m1: (58843,70948) , m2: (72122,70987) , m3: (65767,71983) , m4: (46930,65566) , m5: (65795,72047) , m6: (70644,58001)
TrolleyPos: 32.978, Hoistpos: 38.124, NoOfMarkers: 3, m1: (58843,70948) , m2: (72122,70987) , m3: (65767,71983) , m4: (46930,65566) , m5: (65795,72047) , m6: (70644,58001)
 */
#ifndef SRC_MMT_OCPP_INCLUDE_OCPP_DATA_H_
#define SRC_MMT_OCPP_INCLUDE_OCPP_DATA_H_


#define OCPP_DATA_LEVEL_0_ALIAS "level_0"
#define OCPP_DATA_INDEX_ALIAS "index"
#define OCPP_DATA_FLOW_ID_ALIAS "flow_id"
#define OCPP_DATA_SRC_IP_ALIAS "src_ip"
#define OCPP_DATA_DST_IP_ALIAS "dst_ip"
#define OCPP_DATA_SRC_PORT_ALIAS "src_port"
#define OCPP_DATA_DST_PORT_ALIAS "dst_port"
#define OCPP_DATA_TOTAL_FLOW_PACKETS_ALIAS "total_flow_packets"
#define OCPP_DATA_TOTAL_FW_PACKETS_ALIAS "total_fw_packets"
#define OCPP_DATA_TOTAL_BW_PACKETS_ALIAS "total_bw_packets"
#define OCPP_DATA_FLOW_DURATION_ALIAS "flow_duration"
#define OCPP_DATA_FLOW_DOWN_UP_RATIO_ALIAS "flow_down_up_ratio"
#define OCPP_DATA_FLOW_TOTAL_SYN_FLAG_ALIAS "flow_total_SYN_flag"
#define OCPP_DATA_FLOW_TOTAL_RST_FLAG_ALIAS "flow_total_RST_flag"
#define OCPP_DATA_FLOW_TOTAL_PSH_FLAG_ALIAS "flow_total_PSH_flag"
#define OCPP_DATA_FLOW_TOTAL_ACK_FLAG_ALIAS "flow_total_ACK_flag"
#define OCPP_DATA_FLOW_TOTAL_URG_FLAG_ALIAS "flow_total_URG_flag"
#define OCPP_DATA_FLOW_TOTAL_CWE_FLAG_ALIAS "flow_total_CWE_flag"
#define OCPP_DATA_FLOW_TOTAL_ECE_FLAG_ALIAS "flow_total_ECE_flag"
#define OCPP_DATA_FLOW_TOTAL_FIN_FLAG_ALIAS "flow_total_FIN_flag"
#define OCPP_DATA_FLOW_START_TIMESTAMP_ALIAS "flow_start_timestamp"
#define OCPP_DATA_FLOW_END_TIMESTAMP_ALIAS "flow_end_timestamp"
#define OCPP_DATA_FLOW_TOTAL_HTTP_GET_PACKETS_ALIAS  "flow_total_http_get_packets"
#define OCPP_DATA_FLOW_TOTAL_HTTP_2XX_PACKETS_ALIAS  "flow_total_http_2xx_packets"
#define OCPP_DATA_FLOW_TOTAL_HTTP_4XX_PACKETS_ALIAS  "flow_total_http_4xx_packets"
#define OCPP_DATA_FLOW_TOTAL_HTTP_5XX_PACKETS_ALIAS  "flow_total_http_5xx_packets"
#define OCPP_DATA_FLOW_WEBSOCKET_PACKETS_PER_SECOND_ALIAS	"flow_websocket_packts_per_second"
#define OCPP_DATA_FW_WEBSOCKET_PACKETS_PER_SECOND_ALIAS "fw_websocket_packts_per_second"
#define OCPP_DATA_BW_WEBSOCKET_PACKETS_PER_SECOND_ALIAS "bw_websocket_packts_per_second"
#define OCPP_DATA_FLOW_WEBSOCKET_BYTES_PER_SECOND_ALIAS "flow_websocket_bytes_per_second"
#define OCPP_DATA_FW_WEBSOCKET_BYTES_PER_SECOND_ALIAS "fw_websocket_bytes_per_second"
#define OCPP_DATA_BW_WEBSOCKET_BYTES_PER_SECOND_ALIAS "bw_websocket_bytes_per_second"
#define OCPP_DATA_FLOW_TOTAL_WEBSOCKET_PING_PACKETS_ALIAS "flow_total_websocket_ping_packets"
#define OCPP_DATA_FLOW_TOTAL_WEBSOCKET_PONG_PACKETS_ALIAS "flow_total_websocket_pong_packets"
#define OCPP_DATA_FLOW_TOTAL_WEBSOCKET_CLOSE_PACKETS_ALIAS "flow_total_websocket_close_packets"
#define OCPP_DATA_FLOW_TOTAL_WEBSOCKET_DATA_MESSAGES_ALIAS "flow_total_websocket_data_messages"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_HEARTBEAT_PACKETS_ALIAS "flow_total_ocpp16_heartbeat_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_RESETHARD_PACKETS_ALIAS "flow_total_ocpp16_resetHard_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_RESETSOFT_PACKETS_ALIAS "flow_total_ocpp16_resetSoft_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_UNLOCKCONNECTOR_PACKETS_ALIAS "flow_total_ocpp16_unlockconnector_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_STARTTRANSACTION_PACKETS_ALIAS "flow_total_ocpp16_starttransaction_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_REMOTESTARTTRANSACTION_PACKETS_ALIAS "flow_total_ocpp16_remotestarttransaction_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_AUTHORIZE_NOT_ACCEPTED_PACKETS_ALIAS "flow_total_ocpp16_authorize_not_accepted_packets"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_SETCHARGINGPROFILE_PACKETS_ALIAS "flow_total_ocpp16_setchargingprofile_packets"
#define OCPP_DATA_FLOW_AVG_OCPP16_SETCHARGINGPROFILE_LIMIT_ALIAS "flow_avg_ocpp16_setchargingprofile_limit"
#define OCPP_DATA_FLOW_MAX_OCPP16_SETCHARGINGPROFILE_LIMIT_ALIAS "flow_max_ocpp16_setchargingprofile_limit"
#define OCPP_DATA_FLOW_MIN_OCPP16_SETCHARGINGPROFILE_LIMIT_ALIAS "flow_min_ocpp16_setchargingprofile_limit"
#define OCPP_DATA_FLOW_AVG_OCPP16_SETCHARGINGPROFILE_MINCHARGINGRATE_ALIAS "flow_avg_ocpp16_setchargingprofile_minchargingrate"
#define OCPP_DATA_FLOW_MIN_OCPP16_SETCHARGINGPROFILE_MINCHARGINGRATE_ALIAS "flow_min_ocpp16_setchargingprofile_minchargingrate"
#define OCPP_DATA_FLOW_MAX_OCPP16_SETCHARGINGPROFILE_MINCHARGINGRATE_ALIAS "flow_max_ocpp16_setchargingprofile_minchargingrate"
#define OCPP_DATA_FLOW_TOTAL_OCPP16_METERVALUE_ALIAS "flow_total_ocpp16_metervalues"
#define OCPP_DATA_FLOW_MIN_OCPP16_METERVALUE_SOC_ALIAS "flow_min_ocpp16_metervalues_soc"
#define OCPP_DATA_FLOW_MAX_OCPP16_METERVALUE_SOC_ALIAS "flow_max_ocpp16_metervalues_soc"
#define OCPP_DATA_FLOW_AVG_OCPP16_METERVALUE_WH_DIFF_ALIAS "flow_avg_ocpp16_metervalues_wh_diff"
#define OCPP_DATA_FLOW_MAX_OCPP16_METERVALUE_WH_DIFF_ALIAS "flow_max_ocpp16_metervalues_wh_diff"
#define OCPP_DATA_FLOW_MIN_OCPP16_METERVALUE_WH_DIFF_ALIAS "flow_min_ocpp16_metervalues_wh_diff"


enum {
    OCPP_DATA_LEVEL_0 = 1,
    OCPP_DATA_INDEX,
    OCPP_DATA_FLOW_ID,
    OCPP_DATA_SRC_IP,
    OCPP_DATA_DST_IP,
    OCPP_DATA_SRC_PORT,
    OCPP_DATA_DST_PORT,
    OCPP_DATA_TOTAL_FLOW_PACKETS,
    OCPP_DATA_TOTAL_FW_PACKETS,
    OCPP_DATA_TOTAL_BW_PACKETS,
    OCPP_DATA_FLOW_DURATION,
    OCPP_DATA_FLOW_DOWN_UP_RATIO,
    OCPP_DATA_FLOW_TOTAL_SYN_FLAG,
    OCPP_DATA_FLOW_TOTAL_RST_FLAG,
    OCPP_DATA_FLOW_TOTAL_PSH_FLAG,
    OCPP_DATA_FLOW_TOTAL_ACK_FLAG,
    OCPP_DATA_FLOW_TOTAL_URG_FLAG,
    OCPP_DATA_FLOW_TOTAL_CWE_FLAG,
    OCPP_DATA_FLOW_TOTAL_ECE_FLAG,
    OCPP_DATA_FLOW_TOTAL_FIN_FLAG,
    OCPP_DATA_FLOW_START_TIMESTAMP,
    OCPP_DATA_FLOW_END_TIMESTAMP,
    OCPP_DATA_FLOW_TOTAL_HTTP_GET_PACKETS,
    OCPP_DATA_FLOW_TOTAL_HTTP_2XX_PACKETS,
    OCPP_DATA_FLOW_TOTAL_HTTP_4XX_PACKETS,
    OCPP_DATA_FLOW_TOTAL_HTTP_5XX_PACKETS,
    OCPP_DATA_FLOW_WEBSOCKET_PACKETS_PER_SECOND,
    OCPP_DATA_FW_WEBSOCKET_PACKETS_PER_SECOND,
    OCPP_DATA_BW_WEBSOCKET_PACKETS_PER_SECOND,
    OCPP_DATA_FLOW_WEBSOCKET_BYTES_PER_SECOND,
    OCPP_DATA_FW_WEBSOCKET_BYTES_PER_SECOND,
    OCPP_DATA_BW_WEBSOCKET_BYTES_PER_SECOND,
    OCPP_DATA_FLOW_TOTAL_WEBSOCKET_PING_PACKETS,
    OCPP_DATA_FLOW_TOTAL_WEBSOCKET_PONG_PACKETS,
    OCPP_DATA_FLOW_TOTAL_WEBSOCKET_CLOSE_PACKETS,
    OCPP_DATA_FLOW_TOTAL_WEBSOCKET_DATA_MESSAGES,
    OCPP_DATA_FLOW_TOTAL_OCPP16_HEARTBEAT_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_RESETHARD_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_RESETSOFT_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_UNLOCKCONNECTOR_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_STARTTRANSACTION_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_REMOTESTARTTRANSACTION_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_AUTHORIZE_NOT_ACCEPTED_PACKETS,
    OCPP_DATA_FLOW_TOTAL_OCPP16_SETCHARGINGPROFILE_PACKETS,
    OCPP_DATA_FLOW_AVG_OCPP16_SETCHARGINGPROFILE_LIMIT,
    OCPP_DATA_FLOW_MAX_OCPP16_SETCHARGINGPROFILE_LIMIT,
    OCPP_DATA_FLOW_MIN_OCPP16_SETCHARGINGPROFILE_LIMIT,
    OCPP_DATA_FLOW_AVG_OCPP16_SETCHARGINGPROFILE_MINCHARGINGRATE,
    OCPP_DATA_FLOW_MIN_OCPP16_SETCHARGINGPROFILE_MINCHARGINGRATE,
    OCPP_DATA_FLOW_MAX_OCPP16_SETCHARGINGPROFILE_MINCHARGINGRATE,
    OCPP_DATA_FLOW_TOTAL_OCPP16_METERVALUE,
    OCPP_DATA_FLOW_MIN_OCPP16_METERVALUE_SOC,
    OCPP_DATA_FLOW_MAX_OCPP16_METERVALUE_SOC,
    OCPP_DATA_FLOW_AVG_OCPP16_METERVALUE_WH_DIFF,
    OCPP_DATA_FLOW_MAX_OCPP16_METERVALUE_WH_DIFF,
    OCPP_DATA_FLOW_MIN_OCPP16_METERVALUE_WH_DIFF
};



#endif /* SRC_MMT_BUSINESS_APP_INCLUDE_OCPP_DATA_H_ */
