/*
 * File:   rtsp.h
 * Author: montimage
 *
 * Created on 20 septembre 2011, 14:18
 */

#ifndef RTSP_H
#define	RTSP_H

#ifdef	__cplusplus
extern "C" {
#endif

/**
 * RTSP response codes.
 */

#define MMT_RTSP_CONTINUE 100

#define MMT_RTSP_OK 200
#define MMT_RTSP_CREATED 201
#define MMT_RTSP_LOW_ON_STORAGE_SPACE 250

#define MMT_RTSP_MULTIPLE_CHOICES 300
#define MMT_RTSP_MOVED_PERMANENTLY 301
#define MMT_RTSP_MOVED_TEMPORARELY 302
#define MMT_RTSP_SEE_OTHER 303
#define MMT_RTSP_NOT_MODIFIED 304
#define MMT_RTSP_USE_PROXY 305

#define MMT_RTSP_BAD_REQUEST 400
#define MMT_RTSP_UNAUTHORIZED 401
#define MMT_RTSP_PAYMENT_REQUIRED 402
#define MMT_RTSP_FORBIDDEN 403
#define MMT_RTSP_NOT_FOUND 404
#define MMT_RTSP_METHOD_NOT_ALLOWED 405
#define MMT_RTSP_METHOD_NOT_ACCEPTABLE 406
#define MMT_RTSP_PROXY_AUTHENTICATION_REQUIRED 407
#define MMT_RTSP_REQUEST_TIMEOUT 408
#define MMT_RTSP_GONE 410
#define MMT_RTSP_LENGTH_REQUIRED 411
#define MMT_RTSP_PRECONDITION_FAILED 412
#define MMT_RTSP_REQUEST_ENTITY_TOO_LARGE 413
#define MMT_RTSP_REQUEST_URI_TOO_LONG 414
#define MMT_RTSP_UNSUPPORTED_MEDIA_TYPE 415

#define MMT_RTSP_PARAMETER_NOT_UNDERSTOOD 451
#define MMT_RTSP_CONFERENCE_NOT_FOUND 452
#define MMT_RTSP_NOT_ENOUGH_BANDWIDTH 453
#define MMT_RTSP_SESSION_NOT_FOUND 454
#define MMT_RTSP_METHOD_NOT_VALID_IN_THIS_STATE 455
#define MMT_RTSP_SESSION_NOT_FOUND 454
#define MMT_RTSP_HEADER_FIELD_NOT_VALID_FOR_RESOURCE 456
#define MMT_RTSP_INVALID_RANGE 457
#define MMT_RTSP_PARAMETER_IS_READ_ONLY 458
#define MMT_RTSP_AGGREGATE_OPERATION_NOT_ALLOWED 459
#define MMT_RTSP_ONLY_AGGREGATE_OPERATION_ALLOWED 460
#define MMT_RTSP_UNSUPPORTED_TRANSPORT 461
#define MMT_RTSP_DESTINATION_UNREACHABLE 462

#define MMT_RTSP_INTERNAL_SERVER_ERROR 500
#define MMT_RTSP_NOT_IMPLEMENTED 501
#define MMT_RTSP_BAD_GATEWAY 502
#define MMT_RTSP_SERVICE_UNAVAILABLE 503
#define MMT_RTSP_GATEWAY_TIMEOUT 504
#define MMT_RTSP_RTSP_VERSION_NOT_SUPPORTED 505
#define MMT_RTSP_OPTION_NOT_SUPPORTED 551

#ifdef	__cplusplus
}
#endif

#endif	/* RTSP_H */
