/*
 * dynabic_hes_data.h
 *
 *  Created on: Nov 20, 2024
 *      Author: vietpham
 */


#ifndef SRC_MMT_DYNABIC_HES_INCLUDE_DYNABIC_HES_DATA_H_
#define SRC_MMT_DYNABIC_HES_INCLUDE_DYNABIC_HES_DATA_H_

#define DYNABIC_HES_DATA_TIMESTAMP_ALIAS "timestamp"
#define DYNABIC_HES_DATA_PROTOCOL_ALIAS "protocol"
#define DYNABIC_HES_DATA_SRC_IP_ALIAS "src_ip"
#define DYNABIC_HES_DATA_DST_IP_ALIAS "dst_ip"
#define DYNABIC_HES_DATA_SRC_PORT_ALIAS "src_port"
#define DYNABIC_HES_DATA_DST_PORT_ALIAS "dst_port"
#define DYNABIC_HES_DATA_LENGTH_ALIAS "length"
#define DYNABIC_HES_DATA_TCP_FLAGS_ALIAS "tcp_flags"
#define DYNABIC_HES_DATA_PAYLOAD_SIZE_ALIAS "payload_size"


enum {
    DYNABIC_HES_DATA_TIMESTAMP = 1,
    DYNABIC_HES_DATA_PROTOCOL,
    DYNABIC_HES_DATA_SRC_IP,
    DYNABIC_HES_DATA_DST_IP,
    DYNABIC_HES_DATA_SRC_PORT,
    DYNABIC_HES_DATA_DST_PORT,
    DYNABIC_HES_DATA_LENGTH,
    DYNABIC_HES_DATA_TCP_FLAGS, 
    DYNABIC_HES_DATA_PAYLOAD_SIZE
};


#endif /* SRC_MMT_DYNABIC_HES_INCLUDE_DYNABIC_HES_DATA_H_ */
