/*
 * cicflow_data.h
 *
 *  Created on: May 05, 2024
 *      Author: vietpham
 */

#ifndef SRC_MMT_CICFLOW_INCLUDE_CICFLOW_DATA_H_
#define SRC_MMT_CICFLOW_INCLUDE_CICFLOW_DATA_H_

#define CICFLOW_DATA_FLOW_ID_ALIAS "Flow_ID"
#define CICFLOW_DATA_SRC_IP_ALIAS "Src_IP"
#define CICFLOW_DATA_SRC_PORT_ALIAS "Src_Port"
#define CICFLOW_DATA_DST_IP_ALIAS "Dst_IP"
#define CICFLOW_DATA_DST_PORT_ALIAS "Dst_Port"
#define CICFLOW_DATA_PROTOCOL_ALIAS "Protocol"
#define CICFLOW_DATA_TIMESTAMP_ALIAS "Timestamp"
#define CICFLOW_DATA_FLOW_DURATION_ALIAS "Flow_Duration"
#define CICFLOW_DATA_TOTAL_FWD_PACKET_ALIAS "Total_Fwd_Packet"
#define CICFLOW_DATA_TOTAL_BWD_PACKETS_ALIAS "Total_Bwd_packets"
#define CICFLOW_DATA_TOTAL_LENGTH_OF_FWD_PACKET_ALIAS "Total_Length_of_Fwd_Packet"
#define CICFLOW_DATA_TOTAL_LENGTH_OF_BWD_PACKET_ALIAS "Total_Length_of_Bwd_Packet"
#define CICFLOW_DATA_FWD_PACKET_LENGTH_MAX_ALIAS "Fwd_Packet_Length_Max"
#define CICFLOW_DATA_FWD_PACKET_LENGTH_MIN_ALIAS "Fwd_Packet_Length_Min"
#define CICFLOW_DATA_FWD_PACKET_LENGTH_MEAN_ALIAS "Fwd_Packet_Length_Mean"
#define CICFLOW_DATA_FWD_PACKET_LENGTH_STD_ALIAS "Fwd_Packet_Length_Std"
#define CICFLOW_DATA_BWD_PACKET_LENGTH_MAX_ALIAS "Bwd_Packet_Length_Max"
#define CICFLOW_DATA_BWD_PACKET_LENGTH_MIN_ALIAS "Bwd_Packet_Length_Min"
#define CICFLOW_DATA_BWD_PACKET_LENGTH_MEAN_ALIAS "Bwd_Packet_Length_Mean"
#define CICFLOW_DATA_BWD_PACKET_LENGTH_STD_ALIAS "Bwd_Packet_Length_Std"
#define CICFLOW_DATA_FLOW_BYTES_S_ALIAS "Flow_Bytes_per_s"
#define CICFLOW_DATA_FLOW_PACKETS_S_ALIAS "Flow_Packets_per_s"
#define CICFLOW_DATA_FLOW_IAT_MEAN_ALIAS "Flow_IAT_Mean"
#define CICFLOW_DATA_FLOW_IAT_STD_ALIAS "Flow_IAT_Std"
#define CICFLOW_DATA_FLOW_IAT_MAX_ALIAS "Flow_IAT_Max"
#define CICFLOW_DATA_FLOW_IAT_MIN_ALIAS "Flow_IAT_Min"
#define CICFLOW_DATA_FWD_IAT_TOTAL_ALIAS "Fwd_IAT_Total"
#define CICFLOW_DATA_FWD_IAT_MEAN_ALIAS "Fwd_IAT_Mean"
#define CICFLOW_DATA_FWD_IAT_STD_ALIAS "Fwd_IAT_Std"
#define CICFLOW_DATA_FWD_IAT_MAX_ALIAS "Fwd_IAT_Max"
#define CICFLOW_DATA_FWD_IAT_MIN_ALIAS "Fwd_IAT_Min"
#define CICFLOW_DATA_BWD_IAT_TOTAL_ALIAS "Bwd_IAT_Total"
#define CICFLOW_DATA_BWD_IAT_MEAN_ALIAS "Bwd_IAT_Mean"
#define CICFLOW_DATA_BWD_IAT_STD_ALIAS "Bwd_IAT_Std"
#define CICFLOW_DATA_BWD_IAT_MAX_ALIAS "Bwd_IAT_Max"
#define CICFLOW_DATA_BWD_IAT_MIN_ALIAS "Bwd_IAT_Min"
#define CICFLOW_DATA_FWD_PSH_FLAGS_ALIAS "Fwd_PSH_Flags"
#define CICFLOW_DATA_BWD_PSH_FLAGS_ALIAS "Bwd_PSH_Flags"
#define CICFLOW_DATA_FWD_URG_FLAGS_ALIAS "Fwd_URG_Flags"
#define CICFLOW_DATA_BWD_URG_FLAGS_ALIAS "Bwd_URG_Flags"
#define CICFLOW_DATA_FWD_HEADER_LENGTH_ALIAS "Fwd_Header_Length"
#define CICFLOW_DATA_BWD_HEADER_LENGTH_ALIAS "Bwd_Header_Length"
#define CICFLOW_DATA_FWD_PACKETS_S_ALIAS "Fwd_Packets_per_s"
#define CICFLOW_DATA_BWD_PACKETS_S_ALIAS "Bwd_Packets_per_s"
#define CICFLOW_DATA_PACKET_LENGTH_MIN_ALIAS "Packet_Length_Min"
#define CICFLOW_DATA_PACKET_LENGTH_MAX_ALIAS "Packet_Length_Max"
#define CICFLOW_DATA_PACKET_LENGTH_MEAN_ALIAS "Packet_Length_Mean"
#define CICFLOW_DATA_PACKET_LENGTH_STD_ALIAS "Packet_Length_Std"
#define CICFLOW_DATA_PACKET_LENGTH_VARIANCE_ALIAS "Packet_Length_Variance"
#define CICFLOW_DATA_FIN_FLAG_COUNT_ALIAS "FIN_Flag_Count"
#define CICFLOW_DATA_SYN_FLAG_COUNT_ALIAS "SYN_Flag_Count"
#define CICFLOW_DATA_RST_FLAG_COUNT_ALIAS "RST_Flag_Count"
#define CICFLOW_DATA_PSH_FLAG_COUNT_ALIAS "PSH_Flag_Count"
#define CICFLOW_DATA_ACK_FLAG_COUNT_ALIAS "ACK_Flag_Count"
#define CICFLOW_DATA_URG_FLAG_COUNT_ALIAS "URG_Flag_Count"
#define CICFLOW_DATA_CWR_FLAG_COUNT_ALIAS "CWR_Flag_Count"
#define CICFLOW_DATA_ECE_FLAG_COUNT_ALIAS "ECE_Flag_Count"
#define CICFLOW_DATA_DOWN_UP_RATIO_ALIAS "Down_per_Up_Ratio"
#define CICFLOW_DATA_AVERAGE_PACKET_SIZE_ALIAS "Average_Packet_Size"
#define CICFLOW_DATA_FWD_SEGMENT_SIZE_AVG_ALIAS "Fwd_Segment_Size_Avg"
#define CICFLOW_DATA_BWD_SEGMENT_SIZE_AVG_ALIAS "Bwd_Segment_Size_Avg"
#define CICFLOW_DATA_FWD_BYTES_BULK_AVG_ALIAS "Fwd_Bytes_per_Bulk_Avg"
#define CICFLOW_DATA_FWD_PACKET_BULK_AVG_ALIAS "Fwd_Packet_per_Bulk_Avg"
#define CICFLOW_DATA_FWD_BULK_RATE_AVG_ALIAS "Fwd_Bulk_Rate_Avg"
#define CICFLOW_DATA_BWD_BYTES_BULK_AVG_ALIAS "Bwd_Bytes_per_Bulk_Avg"
#define CICFLOW_DATA_BWD_PACKET_BULK_AVG_ALIAS "Bwd_Packet_per_Bulk_Avg"
#define CICFLOW_DATA_BWD_BULK_RATE_AVG_ALIAS "Bwd_Bulk_Rate_Avg"
#define CICFLOW_DATA_SUBFLOW_FWD_PACKETS_ALIAS "Subflow_Fwd_Packets"
#define CICFLOW_DATA_SUBFLOW_FWD_BYTES_ALIAS "Subflow_Fwd_Bytes"
#define CICFLOW_DATA_SUBFLOW_BWD_PACKETS_ALIAS "Subflow_Bwd_Packets"
#define CICFLOW_DATA_SUBFLOW_BWD_BYTES_ALIAS "Subflow_Bwd_Bytes"
#define CICFLOW_DATA_FWD_INIT_WIN_BYTES_ALIAS "FWD_Init_Win_Bytes"
#define CICFLOW_DATA_BWD_INIT_WIN_BYTES_ALIAS "Bwd_Init_Win_Bytes"
#define CICFLOW_DATA_FWD_ACT_DATA_PKTS_ALIAS "Fwd_Act_Data_Pkts"
#define CICFLOW_DATA_FWD_SEG_SIZE_MIN_ALIAS "Fwd_Seg_Size_Min"
#define CICFLOW_DATA_ACTIVE_MEAN_ALIAS "Active_Mean"
#define CICFLOW_DATA_ACTIVE_STD_ALIAS "Active_Std"
#define CICFLOW_DATA_ACTIVE_MAX_ALIAS "Active_Max"
#define CICFLOW_DATA_ACTIVE_MIN_ALIAS "Active_Min"
#define CICFLOW_DATA_IDLE_MEAN_ALIAS "Idle_Mean"
#define CICFLOW_DATA_IDLE_STD_ALIAS "Idle_Std"
#define CICFLOW_DATA_IDLE_MAX_ALIAS "Idle_Max"
#define CICFLOW_DATA_IDLE_MIN_ALIAS "Idle_Min"
#define CICFLOW_DATA_LABEL_ALIAS "Label"
#define CICFLOW_DATA_ID_ALIAS "id"

enum {
    CICFLOW_DATA_FLOW_ID = 1,
    CICFLOW_DATA_SRC_IP,
    CICFLOW_DATA_DST_IP,
    CICFLOW_DATA_SRC_PORT,
    CICFLOW_DATA_DST_PORT,
    CICFLOW_DATA_PROTOCOL,
    CICFLOW_DATA_TIMESTAMP,
    CICFLOW_DATA_FLOW_DURATION,
    CICFLOW_DATA_TOTAL_FWD_PACKET,
    CICFLOW_DATA_TOTAL_BWD_PACKETS,
    CICFLOW_DATA_TOTAL_LENGTH_OF_FWD_PACKET,
    CICFLOW_DATA_TOTAL_LENGTH_OF_BWD_PACKET,
    CICFLOW_DATA_FWD_PACKET_LENGTH_MAX,
    CICFLOW_DATA_FWD_PACKET_LENGTH_MIN,
    CICFLOW_DATA_FWD_PACKET_LENGTH_MEAN,
    CICFLOW_DATA_FWD_PACKET_LENGTH_STD,
    CICFLOW_DATA_BWD_PACKET_LENGTH_MAX,
    CICFLOW_DATA_BWD_PACKET_LENGTH_MIN,
    CICFLOW_DATA_BWD_PACKET_LENGTH_MEAN,
    CICFLOW_DATA_BWD_PACKET_LENGTH_STD,
    CICFLOW_DATA_FLOW_BYTES_S,
    CICFLOW_DATA_FLOW_PACKETS_S,
    CICFLOW_DATA_FLOW_IAT_MEAN,
    CICFLOW_DATA_FLOW_IAT_STD,
    CICFLOW_DATA_FLOW_IAT_MAX,
    CICFLOW_DATA_FLOW_IAT_MIN,
    CICFLOW_DATA_FWD_IAT_TOTAL,
    CICFLOW_DATA_FWD_IAT_MEAN,
    CICFLOW_DATA_FWD_IAT_STD,
    CICFLOW_DATA_FWD_IAT_MAX,
    CICFLOW_DATA_FWD_IAT_MIN,
    CICFLOW_DATA_BWD_IAT_TOTAL,
    CICFLOW_DATA_BWD_IAT_MEAN,
    CICFLOW_DATA_BWD_IAT_STD,
    CICFLOW_DATA_BWD_IAT_MAX,
    CICFLOW_DATA_BWD_IAT_MIN,
    CICFLOW_DATA_FWD_PSH_FLAGS,
    CICFLOW_DATA_BWD_PSH_FLAGS,
    CICFLOW_DATA_FWD_URG_FLAGS,
    CICFLOW_DATA_BWD_URG_FLAGS,
    CICFLOW_DATA_FWD_HEADER_LENGTH,
    CICFLOW_DATA_BWD_HEADER_LENGTH,
    CICFLOW_DATA_FWD_PACKETS_S,
    CICFLOW_DATA_BWD_PACKETS_S,
    CICFLOW_DATA_PACKET_LENGTH_MIN,
    CICFLOW_DATA_PACKET_LENGTH_MAX,
    CICFLOW_DATA_PACKET_LENGTH_MEAN,
    CICFLOW_DATA_PACKET_LENGTH_STD,
    CICFLOW_DATA_PACKET_LENGTH_VARIANCE,
    CICFLOW_DATA_FIN_FLAG_COUNT,
    CICFLOW_DATA_SYN_FLAG_COUNT,
    CICFLOW_DATA_RST_FLAG_COUNT,
    CICFLOW_DATA_PSH_FLAG_COUNT,
    CICFLOW_DATA_ACK_FLAG_COUNT,
    CICFLOW_DATA_URG_FLAG_COUNT,
    CICFLOW_DATA_CWR_FLAG_COUNT,
    CICFLOW_DATA_ECE_FLAG_COUNT,
    CICFLOW_DATA_DOWN_UP_RATIO,
    CICFLOW_DATA_AVERAGE_PACKET_SIZE,
    CICFLOW_DATA_FWD_SEGMENT_SIZE_AVG,
    CICFLOW_DATA_BWD_SEGMENT_SIZE_AVG,
    CICFLOW_DATA_FWD_BYTES_BULK_AVG,
    CICFLOW_DATA_FWD_PACKET_BULK_AVG,
    CICFLOW_DATA_FWD_BULK_RATE_AVG,
    CICFLOW_DATA_BWD_BYTES_BULK_AVG,
    CICFLOW_DATA_BWD_PACKET_BULK_AVG,
    CICFLOW_DATA_BWD_BULK_RATE_AVG,
    CICFLOW_DATA_SUBFLOW_FWD_PACKETS,
    CICFLOW_DATA_SUBFLOW_FWD_BYTES,
    CICFLOW_DATA_SUBFLOW_BWD_PACKETS,
    CICFLOW_DATA_SUBFLOW_BWD_BYTES,
    CICFLOW_DATA_FWD_INIT_WIN_BYTES,
    CICFLOW_DATA_BWD_INIT_WIN_BYTES,
    CICFLOW_DATA_FWD_ACT_DATA_PKTS,
    CICFLOW_DATA_FWD_SEG_SIZE_MIN,
    CICFLOW_DATA_ACTIVE_MEAN,
    CICFLOW_DATA_ACTIVE_STD,
    CICFLOW_DATA_ACTIVE_MAX,
    CICFLOW_DATA_ACTIVE_MIN,
    CICFLOW_DATA_IDLE_MEAN,
    CICFLOW_DATA_IDLE_STD,
    CICFLOW_DATA_IDLE_MAX,
    CICFLOW_DATA_IDLE_MIN,
    CICFLOW_DATA_LABEL,
    CICFLOW_DATA_ID
};

#endif /* SRC_MMT_BUSINESS_APP_INCLUDE_CICFLOW_DATA_H_ */