/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./support/s1ap-r10.5.0/S1AP-IEs.asn"
 * 	`asn1c -D ./common -gen-PER -pdu=all -fcompound-names -fno-include-deps -no-gen-example`
 */

#ifndef	_S1ap_Bearers_SubjectToStatusTransfer_List_H_
#define	_S1ap_Bearers_SubjectToStatusTransfer_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1ap_IE;

/* S1ap-Bearers-SubjectToStatusTransfer-List */
typedef struct S1ap_Bearers_SubjectToStatusTransfer_List {
	A_SEQUENCE_OF(struct S1ap_IE) list;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_Bearers_SubjectToStatusTransfer_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_Bearers_SubjectToStatusTransfer_List;
extern asn_SET_OF_specifics_t asn_SPC_S1ap_Bearers_SubjectToStatusTransfer_List_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_Bearers_SubjectToStatusTransfer_List_1[1];
extern asn_per_constraints_t asn_PER_type_S1ap_Bearers_SubjectToStatusTransfer_List_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_Bearers_SubjectToStatusTransfer_List_H_ */
#include <asn_internal.h>
