/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-CommonDataTypes"
 * 	found in "./support/s1ap-r10.5.0/S1AP-CommonDataTypes.asn"
 * 	`asn1c -D ./s1ap -gen-PER -fcompound-names`
 */

#ifndef	_S1ap_ProcedureCode_H_
#define	_S1ap_ProcedureCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_ProcedureCode {
	S1ap_ProcedureCode_id_HandoverPreparation	= 0,
	S1ap_ProcedureCode_id_HandoverResourceAllocation	= 1,
	S1ap_ProcedureCode_id_HandoverNotification	= 2,
	S1ap_ProcedureCode_id_PathSwitchRequest	= 3,
	S1ap_ProcedureCode_id_HandoverCancel	= 4,
	S1ap_ProcedureCode_id_E_RABSetup	= 5,
	S1ap_ProcedureCode_id_E_RABModify	= 6,
	S1ap_ProcedureCode_id_E_RABRelease	= 7,
	S1ap_ProcedureCode_id_E_RABReleaseIndication	= 8,
	S1ap_ProcedureCode_id_InitialContextSetup	= 9,
	S1ap_ProcedureCode_id_Paging	= 10,
	S1ap_ProcedureCode_id_downlinkNASTransport	= 11,
	S1ap_ProcedureCode_id_initialUEMessage	= 12,
	S1ap_ProcedureCode_id_uplinkNASTransport	= 13,
	S1ap_ProcedureCode_id_Reset	= 14,
	S1ap_ProcedureCode_id_ErrorIndication	= 15,
	S1ap_ProcedureCode_id_NASNonDeliveryIndication	= 16,
	S1ap_ProcedureCode_id_S1Setup	= 17,
	S1ap_ProcedureCode_id_UEContextReleaseRequest	= 18,
	S1ap_ProcedureCode_id_DownlinkS1cdma2000tunneling	= 19,
	S1ap_ProcedureCode_id_UplinkS1cdma2000tunneling	= 20,
	S1ap_ProcedureCode_id_UEContextModification	= 21,
	S1ap_ProcedureCode_id_UECapabilityInfoIndication	= 22,
	S1ap_ProcedureCode_id_UEContextRelease	= 23,
	S1ap_ProcedureCode_id_eNBStatusTransfer	= 24,
	S1ap_ProcedureCode_id_MMEStatusTransfer	= 25,
	S1ap_ProcedureCode_id_DeactivateTrace	= 26,
	S1ap_ProcedureCode_id_TraceStart	= 27,
	S1ap_ProcedureCode_id_TraceFailureIndication	= 28,
	S1ap_ProcedureCode_id_ENBConfigurationUpdate	= 29,
	S1ap_ProcedureCode_id_MMEConfigurationUpdate	= 30,
	S1ap_ProcedureCode_id_LocationReportingControl	= 31,
	S1ap_ProcedureCode_id_LocationReportingFailureIndication	= 32,
	S1ap_ProcedureCode_id_LocationReport	= 33,
	S1ap_ProcedureCode_id_OverloadStart	= 34,
	S1ap_ProcedureCode_id_OverloadStop	= 35,
	S1ap_ProcedureCode_id_WriteReplaceWarning	= 36,
	S1ap_ProcedureCode_id_eNBDirectInformationTransfer	= 37,
	S1ap_ProcedureCode_id_MMEDirectInformationTransfer	= 38,
	S1ap_ProcedureCode_id_PrivateMessage	= 39,
	S1ap_ProcedureCode_id_eNBConfigurationTransfer	= 40,
	S1ap_ProcedureCode_id_MMEConfigurationTransfer	= 41,
	S1ap_ProcedureCode_id_CellTrafficTrace	= 42,
	S1ap_ProcedureCode_id_Kill	= 43,
	S1ap_ProcedureCode_id_downlinkUEAssociatedLPPaTransport	= 44,
	S1ap_ProcedureCode_id_uplinkUEAssociatedLPPaTransport	= 45,
	S1ap_ProcedureCode_id_downlinkNonUEAssociatedLPPaTransport	= 46,
	S1ap_ProcedureCode_id_uplinkNonUEAssociatedLPPaTransport	= 47
} e_S1ap_ProcedureCode;

/* S1ap-ProcedureCode */
typedef long	 S1ap_ProcedureCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_S1ap_ProcedureCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_S1ap_ProcedureCode;
asn_struct_free_f S1ap_ProcedureCode_free;
asn_struct_print_f S1ap_ProcedureCode_print;
asn_constr_check_f S1ap_ProcedureCode_constraint;
ber_type_decoder_f S1ap_ProcedureCode_decode_ber;
der_type_encoder_f S1ap_ProcedureCode_encode_der;
xer_type_decoder_f S1ap_ProcedureCode_decode_xer;
xer_type_encoder_f S1ap_ProcedureCode_encode_xer;
oer_type_decoder_f S1ap_ProcedureCode_decode_oer;
oer_type_encoder_f S1ap_ProcedureCode_encode_oer;
per_type_decoder_f S1ap_ProcedureCode_decode_uper;
per_type_encoder_f S1ap_ProcedureCode_encode_uper;
per_type_decoder_f S1ap_ProcedureCode_decode_aper;
per_type_encoder_f S1ap_ProcedureCode_encode_aper;
#define S1ap_ProcedureCode_id_HandoverPreparation	((S1ap_ProcedureCode_t)0)
#define S1ap_ProcedureCode_id_HandoverResourceAllocation	((S1ap_ProcedureCode_t)1)
#define S1ap_ProcedureCode_id_HandoverNotification	((S1ap_ProcedureCode_t)2)
#define S1ap_ProcedureCode_id_PathSwitchRequest	((S1ap_ProcedureCode_t)3)
#define S1ap_ProcedureCode_id_HandoverCancel	((S1ap_ProcedureCode_t)4)
#define S1ap_ProcedureCode_id_E_RABSetup	((S1ap_ProcedureCode_t)5)
#define S1ap_ProcedureCode_id_E_RABModify	((S1ap_ProcedureCode_t)6)
#define S1ap_ProcedureCode_id_E_RABRelease	((S1ap_ProcedureCode_t)7)
#define S1ap_ProcedureCode_id_E_RABReleaseIndication	((S1ap_ProcedureCode_t)8)
#define S1ap_ProcedureCode_id_InitialContextSetup	((S1ap_ProcedureCode_t)9)
#define S1ap_ProcedureCode_id_Paging	((S1ap_ProcedureCode_t)10)
#define S1ap_ProcedureCode_id_downlinkNASTransport	((S1ap_ProcedureCode_t)11)
#define S1ap_ProcedureCode_id_initialUEMessage	((S1ap_ProcedureCode_t)12)
#define S1ap_ProcedureCode_id_uplinkNASTransport	((S1ap_ProcedureCode_t)13)
#define S1ap_ProcedureCode_id_Reset	((S1ap_ProcedureCode_t)14)
#define S1ap_ProcedureCode_id_ErrorIndication	((S1ap_ProcedureCode_t)15)
#define S1ap_ProcedureCode_id_NASNonDeliveryIndication	((S1ap_ProcedureCode_t)16)
#define S1ap_ProcedureCode_id_S1Setup	((S1ap_ProcedureCode_t)17)
#define S1ap_ProcedureCode_id_UEContextReleaseRequest	((S1ap_ProcedureCode_t)18)
#define S1ap_ProcedureCode_id_DownlinkS1cdma2000tunneling	((S1ap_ProcedureCode_t)19)
#define S1ap_ProcedureCode_id_UplinkS1cdma2000tunneling	((S1ap_ProcedureCode_t)20)
#define S1ap_ProcedureCode_id_UEContextModification	((S1ap_ProcedureCode_t)21)
#define S1ap_ProcedureCode_id_UECapabilityInfoIndication	((S1ap_ProcedureCode_t)22)
#define S1ap_ProcedureCode_id_UEContextRelease	((S1ap_ProcedureCode_t)23)
#define S1ap_ProcedureCode_id_eNBStatusTransfer	((S1ap_ProcedureCode_t)24)
#define S1ap_ProcedureCode_id_MMEStatusTransfer	((S1ap_ProcedureCode_t)25)
#define S1ap_ProcedureCode_id_DeactivateTrace	((S1ap_ProcedureCode_t)26)
#define S1ap_ProcedureCode_id_TraceStart	((S1ap_ProcedureCode_t)27)
#define S1ap_ProcedureCode_id_TraceFailureIndication	((S1ap_ProcedureCode_t)28)
#define S1ap_ProcedureCode_id_ENBConfigurationUpdate	((S1ap_ProcedureCode_t)29)
#define S1ap_ProcedureCode_id_MMEConfigurationUpdate	((S1ap_ProcedureCode_t)30)
#define S1ap_ProcedureCode_id_LocationReportingControl	((S1ap_ProcedureCode_t)31)
#define S1ap_ProcedureCode_id_LocationReportingFailureIndication	((S1ap_ProcedureCode_t)32)
#define S1ap_ProcedureCode_id_LocationReport	((S1ap_ProcedureCode_t)33)
#define S1ap_ProcedureCode_id_OverloadStart	((S1ap_ProcedureCode_t)34)
#define S1ap_ProcedureCode_id_OverloadStop	((S1ap_ProcedureCode_t)35)
#define S1ap_ProcedureCode_id_WriteReplaceWarning	((S1ap_ProcedureCode_t)36)
#define S1ap_ProcedureCode_id_eNBDirectInformationTransfer	((S1ap_ProcedureCode_t)37)
#define S1ap_ProcedureCode_id_MMEDirectInformationTransfer	((S1ap_ProcedureCode_t)38)
#define S1ap_ProcedureCode_id_PrivateMessage	((S1ap_ProcedureCode_t)39)
#define S1ap_ProcedureCode_id_eNBConfigurationTransfer	((S1ap_ProcedureCode_t)40)
#define S1ap_ProcedureCode_id_MMEConfigurationTransfer	((S1ap_ProcedureCode_t)41)
#define S1ap_ProcedureCode_id_CellTrafficTrace	((S1ap_ProcedureCode_t)42)
#define S1ap_ProcedureCode_id_Kill	((S1ap_ProcedureCode_t)43)
#define S1ap_ProcedureCode_id_downlinkUEAssociatedLPPaTransport	((S1ap_ProcedureCode_t)44)
#define S1ap_ProcedureCode_id_uplinkUEAssociatedLPPaTransport	((S1ap_ProcedureCode_t)45)
#define S1ap_ProcedureCode_id_downlinkNonUEAssociatedLPPaTransport	((S1ap_ProcedureCode_t)46)
#define S1ap_ProcedureCode_id_uplinkNonUEAssociatedLPPaTransport	((S1ap_ProcedureCode_t)47)

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_ProcedureCode_H_ */
#include <asn_internal.h>
