/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./support/s1ap-r10.5.0/S1AP-IEs.asn"
 * 	`asn1c -D ./common -gen-PER -pdu=all -fcompound-names -fno-include-deps -no-gen-example`
 */

#ifndef	_S1ap_ENB_ID_H_
#define	_S1ap_ENB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_ENB_ID_PR {
	S1ap_ENB_ID_PR_NOTHING,	/* No components present */
	S1ap_ENB_ID_PR_macroENB_ID,
	S1ap_ENB_ID_PR_homeENB_ID
	/* Extensions may appear below */

} S1ap_ENB_ID_PR;

/* S1ap-ENB-ID */
typedef struct S1ap_ENB_ID {
	S1ap_ENB_ID_PR present;
	union S1ap_ENB_ID_u {
		BIT_STRING_t	 macroENB_ID;
		BIT_STRING_t	 homeENB_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_ENB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_ENB_ID;
extern asn_CHOICE_specifics_t asn_SPC_S1ap_ENB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_ENB_ID_1[2];
extern asn_per_constraints_t asn_PER_type_S1ap_ENB_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_ENB_ID_H_ */
#include <asn_internal.h>
