/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./support/s1ap-r10.5.0/S1AP-IEs.asn"
 * 	`asn1c -D ./common -gen-PER -pdu=all -fcompound-names -fno-include-deps -no-gen-example`
 */

#include "S1ap-NASSecurityParameterstoE-UTRAN.h"

/*
 * This type is implemented using OCTET_STRING,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (4 << 2))
};
asn_TYPE_descriptor_t asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN = {
	"S1ap-NASSecurityParameterstoE-UTRAN",
	"S1ap-NASSecurityParameterstoE-UTRAN",
	&asn_OP_OCTET_STRING,
	asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1,
	sizeof(asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1)
		/sizeof(asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1[0]), /* 1 */
	asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1,	/* Same as above */
	sizeof(asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1)
		/sizeof(asn_DEF_S1ap_NASSecurityParameterstoE_UTRAN_tags_1[0]), /* 1 */
	{ 0, 0, OCTET_STRING_constraint },
	0, 0,	/* No members */
	&asn_SPC_OCTET_STRING_specs	/* Additional specs */
};
