/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./support/s1ap-r10.5.0/S1AP-IEs.asn"
 * 	`asn1c -D ./common -gen-PER -pdu=all -fcompound-names -fno-include-deps -no-gen-example`
 */

#include "S1ap-AreaScopeOfMDT.h"

static asn_oer_constraints_t asn_OER_type_S1ap_AreaScopeOfMDT_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_S1ap_AreaScopeOfMDT_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_S1ap_AreaScopeOfMDT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_AreaScopeOfMDT, choice.cellBased),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1ap_CellBasedMDT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellBased"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_AreaScopeOfMDT, choice.tABased),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1ap_TABasedMDT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tABased"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_AreaScopeOfMDT, choice.pLMNWide),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pLMNWide"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_S1ap_AreaScopeOfMDT_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellBased */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tABased */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* pLMNWide */
};
asn_CHOICE_specifics_t asn_SPC_S1ap_AreaScopeOfMDT_specs_1 = {
	sizeof(struct S1ap_AreaScopeOfMDT),
	offsetof(struct S1ap_AreaScopeOfMDT, _asn_ctx),
	offsetof(struct S1ap_AreaScopeOfMDT, present),
	sizeof(((struct S1ap_AreaScopeOfMDT *)0)->present),
	asn_MAP_S1ap_AreaScopeOfMDT_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_S1ap_AreaScopeOfMDT = {
	"S1ap-AreaScopeOfMDT",
	"S1ap-AreaScopeOfMDT",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_S1ap_AreaScopeOfMDT_constr_1, &asn_PER_type_S1ap_AreaScopeOfMDT_constr_1, CHOICE_constraint },
	asn_MBR_S1ap_AreaScopeOfMDT_1,
	3,	/* Elements count */
	&asn_SPC_S1ap_AreaScopeOfMDT_specs_1	/* Additional specs */
};

