/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-CommonDataTypes"
 * 	found in "./support/s1ap-r10.5.0/S1AP-CommonDataTypes.asn"
 * 	`asn1c -D ./s1ap -gen-PER -fcompound-names`
 */

#ifndef	_S1ap_ProtocolIE_ID_H_
#define	_S1ap_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_ProtocolIE_ID {
	S1ap_ProtocolIE_ID_id_MME_UE_S1AP_ID	= 0,
	S1ap_ProtocolIE_ID_id_HandoverType	= 1,
	S1ap_ProtocolIE_ID_id_Cause	= 2,
	S1ap_ProtocolIE_ID_id_SourceID	= 3,
	S1ap_ProtocolIE_ID_id_TargetID	= 4,
	S1ap_ProtocolIE_ID_id_eNB_UE_S1AP_ID	= 8,
	S1ap_ProtocolIE_ID_id_E_RABSubjecttoDataForwardingList	= 12,
	S1ap_ProtocolIE_ID_id_E_RABtoReleaseListHOCmd	= 13,
	S1ap_ProtocolIE_ID_id_E_RABDataForwardingItem	= 14,
	S1ap_ProtocolIE_ID_id_E_RABReleaseItemBearerRelComp	= 15,
	S1ap_ProtocolIE_ID_id_E_RABToBeSetupListBearerSUReq	= 16,
	S1ap_ProtocolIE_ID_id_E_RABToBeSetupItemBearerSUReq	= 17,
	S1ap_ProtocolIE_ID_id_E_RABAdmittedList	= 18,
	S1ap_ProtocolIE_ID_id_E_RABFailedToSetupListHOReqAck	= 19,
	S1ap_ProtocolIE_ID_id_E_RABAdmittedItem	= 20,
	S1ap_ProtocolIE_ID_id_E_RABFailedToSetupItemHOReqAck	= 21,
	S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedDLList	= 22,
	S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedDLItem	= 23,
	S1ap_ProtocolIE_ID_id_E_RABToBeSetupListCtxtSUReq	= 24,
	S1ap_ProtocolIE_ID_id_TraceActivation	= 25,
	S1ap_ProtocolIE_ID_id_NAS_PDU	= 26,
	S1ap_ProtocolIE_ID_id_E_RABToBeSetupItemHOReq	= 27,
	S1ap_ProtocolIE_ID_id_E_RABSetupListBearerSURes	= 28,
	S1ap_ProtocolIE_ID_id_E_RABFailedToSetupListBearerSURes	= 29,
	S1ap_ProtocolIE_ID_id_E_RABToBeModifiedListBearerModReq	= 30,
	S1ap_ProtocolIE_ID_id_E_RABModifyListBearerModRes	= 31,
	S1ap_ProtocolIE_ID_id_E_RABFailedToModifyList	= 32,
	S1ap_ProtocolIE_ID_id_E_RABToBeReleasedList	= 33,
	S1ap_ProtocolIE_ID_id_E_RABFailedToReleaseList	= 34,
	S1ap_ProtocolIE_ID_id_E_RABItem	= 35,
	S1ap_ProtocolIE_ID_id_E_RABToBeModifiedItemBearerModReq	= 36,
	S1ap_ProtocolIE_ID_id_E_RABModifyItemBearerModRes	= 37,
	S1ap_ProtocolIE_ID_id_E_RABReleaseItem	= 38,
	S1ap_ProtocolIE_ID_id_E_RABSetupItemBearerSURes	= 39,
	S1ap_ProtocolIE_ID_id_SecurityContext	= 40,
	S1ap_ProtocolIE_ID_id_HandoverRestrictionList	= 41,
	S1ap_ProtocolIE_ID_id_UEPagingID	= 43,
	S1ap_ProtocolIE_ID_id_pagingDRX	= 44,
	S1ap_ProtocolIE_ID_id_TAIList	= 46,
	S1ap_ProtocolIE_ID_id_TAIItem	= 47,
	S1ap_ProtocolIE_ID_id_E_RABFailedToSetupListCtxtSURes	= 48,
	S1ap_ProtocolIE_ID_id_E_RABReleaseItemHOCmd	= 49,
	S1ap_ProtocolIE_ID_id_E_RABSetupItemCtxtSURes	= 50,
	S1ap_ProtocolIE_ID_id_E_RABSetupListCtxtSURes	= 51,
	S1ap_ProtocolIE_ID_id_E_RABToBeSetupItemCtxtSUReq	= 52,
	S1ap_ProtocolIE_ID_id_E_RABToBeSetupListHOReq	= 53,
	S1ap_ProtocolIE_ID_id_GERANtoLTEHOInformationRes	= 55,
	S1ap_ProtocolIE_ID_id_UTRANtoLTEHOInformationRes	= 57,
	S1ap_ProtocolIE_ID_id_CriticalityDiagnostics	= 58,
	S1ap_ProtocolIE_ID_id_Global_ENB_ID	= 59,
	S1ap_ProtocolIE_ID_id_eNBname	= 60,
	S1ap_ProtocolIE_ID_id_MMEname	= 61,
	S1ap_ProtocolIE_ID_id_ServedPLMNs	= 63,
	S1ap_ProtocolIE_ID_id_SupportedTAs	= 64,
	S1ap_ProtocolIE_ID_id_TimeToWait	= 65,
	S1ap_ProtocolIE_ID_id_uEaggregateMaximumBitrate	= 66,
	S1ap_ProtocolIE_ID_id_TAI	= 67,
	S1ap_ProtocolIE_ID_id_E_RABReleaseListBearerRelComp	= 69,
	S1ap_ProtocolIE_ID_id_cdma2000PDU	= 70,
	S1ap_ProtocolIE_ID_id_cdma2000RATType	= 71,
	S1ap_ProtocolIE_ID_id_cdma2000SectorID	= 72,
	S1ap_ProtocolIE_ID_id_SecurityKey	= 73,
	S1ap_ProtocolIE_ID_id_UERadioCapability	= 74,
	S1ap_ProtocolIE_ID_id_GUMMEI_ID	= 75,
	S1ap_ProtocolIE_ID_id_E_RABInformationListItem	= 78,
	S1ap_ProtocolIE_ID_id_Direct_Forwarding_Path_Availability	= 79,
	S1ap_ProtocolIE_ID_id_UEIdentityIndexValue	= 80,
	S1ap_ProtocolIE_ID_id_cdma2000HOStatus	= 83,
	S1ap_ProtocolIE_ID_id_cdma2000HORequiredIndication	= 84,
	S1ap_ProtocolIE_ID_id_E_UTRAN_Trace_ID	= 86,
	S1ap_ProtocolIE_ID_id_RelativeMMECapacity	= 87,
	S1ap_ProtocolIE_ID_id_SourceMME_UE_S1AP_ID	= 88,
	S1ap_ProtocolIE_ID_id_Bearers_SubjectToStatusTransfer_Item	= 89,
	S1ap_ProtocolIE_ID_id_eNB_StatusTransfer_TransparentContainer	= 90,
	S1ap_ProtocolIE_ID_id_UE_associatedLogicalS1_ConnectionItem	= 91,
	S1ap_ProtocolIE_ID_id_ResetType	= 92,
	S1ap_ProtocolIE_ID_id_UE_associatedLogicalS1_ConnectionListResAck	= 93,
	S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedULItem	= 94,
	S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedULList	= 95,
	S1ap_ProtocolIE_ID_id_S_TMSI	= 96,
	S1ap_ProtocolIE_ID_id_cdma2000OneXRAND	= 97,
	S1ap_ProtocolIE_ID_id_RequestType	= 98,
	S1ap_ProtocolIE_ID_id_UE_S1AP_IDs	= 99,
	S1ap_ProtocolIE_ID_id_EUTRAN_CGI	= 100,
	S1ap_ProtocolIE_ID_id_OverloadResponse	= 101,
	S1ap_ProtocolIE_ID_id_cdma2000OneXSRVCCInfo	= 102,
	S1ap_ProtocolIE_ID_id_E_RABFailedToBeReleasedList	= 103,
	S1ap_ProtocolIE_ID_id_Source_ToTarget_TransparentContainer	= 104,
	S1ap_ProtocolIE_ID_id_ServedGUMMEIs	= 105,
	S1ap_ProtocolIE_ID_id_SubscriberProfileIDforRFP	= 106,
	S1ap_ProtocolIE_ID_id_UESecurityCapabilities	= 107,
	S1ap_ProtocolIE_ID_id_CSFallbackIndicator	= 108,
	S1ap_ProtocolIE_ID_id_CNDomain	= 109,
	S1ap_ProtocolIE_ID_id_E_RABReleasedList	= 110,
	S1ap_ProtocolIE_ID_id_MessageIdentifier	= 111,
	S1ap_ProtocolIE_ID_id_SerialNumber	= 112,
	S1ap_ProtocolIE_ID_id_WarningAreaList	= 113,
	S1ap_ProtocolIE_ID_id_RepetitionPeriod	= 114,
	S1ap_ProtocolIE_ID_id_NumberofBroadcastRequest	= 115,
	S1ap_ProtocolIE_ID_id_WarningType	= 116,
	S1ap_ProtocolIE_ID_id_WarningSecurityInfo	= 117,
	S1ap_ProtocolIE_ID_id_DataCodingScheme	= 118,
	S1ap_ProtocolIE_ID_id_WarningMessageContents	= 119,
	S1ap_ProtocolIE_ID_id_BroadcastCompletedAreaList	= 120,
	S1ap_ProtocolIE_ID_id_Inter_SystemInformationTransferTypeEDT	= 121,
	S1ap_ProtocolIE_ID_id_Inter_SystemInformationTransferTypeMDT	= 122,
	S1ap_ProtocolIE_ID_id_Target_ToSource_TransparentContainer	= 123,
	S1ap_ProtocolIE_ID_id_SRVCCOperationPossible	= 124,
	S1ap_ProtocolIE_ID_id_SRVCCHOIndication	= 125,
	S1ap_ProtocolIE_ID_id_NAS_DownlinkCount	= 126,
	S1ap_ProtocolIE_ID_id_CSG_Id	= 127,
	S1ap_ProtocolIE_ID_id_CSG_IdList	= 128,
	S1ap_ProtocolIE_ID_id_SONConfigurationTransferECT	= 129,
	S1ap_ProtocolIE_ID_id_SONConfigurationTransferMCT	= 130,
	S1ap_ProtocolIE_ID_id_TraceCollectionEntityIPAddress	= 131,
	S1ap_ProtocolIE_ID_id_MSClassmark2	= 132,
	S1ap_ProtocolIE_ID_id_MSClassmark3	= 133,
	S1ap_ProtocolIE_ID_id_RRC_Establishment_Cause	= 134,
	S1ap_ProtocolIE_ID_id_NASSecurityParametersfromE_UTRAN	= 135,
	S1ap_ProtocolIE_ID_id_NASSecurityParameterstoE_UTRAN	= 136,
	S1ap_ProtocolIE_ID_id_DefaultPagingDRX	= 137,
	S1ap_ProtocolIE_ID_id_Source_ToTarget_TransparentContainer_Secondary	= 138,
	S1ap_ProtocolIE_ID_id_Target_ToSource_TransparentContainer_Secondary	= 139,
	S1ap_ProtocolIE_ID_id_EUTRANRoundTripDelayEstimationInfo	= 140,
	S1ap_ProtocolIE_ID_id_BroadcastCancelledAreaList	= 141,
	S1ap_ProtocolIE_ID_id_ConcurrentWarningMessageIndicator	= 142,
	S1ap_ProtocolIE_ID_id_Data_Forwarding_Not_Possible	= 143,
	S1ap_ProtocolIE_ID_id_ExtendedRepetitionPeriod	= 144,
	S1ap_ProtocolIE_ID_id_CellAccessMode	= 145,
	S1ap_ProtocolIE_ID_id_CSGMembershipStatus	= 146,
	S1ap_ProtocolIE_ID_id_LPPa_PDU	= 147,
	S1ap_ProtocolIE_ID_id_Routing_ID	= 148,
	S1ap_ProtocolIE_ID_id_Time_Synchronization_Info	= 149,
	S1ap_ProtocolIE_ID_id_PS_ServiceNotAvailable	= 150,
	S1ap_ProtocolIE_ID_id_PagingPriority	= 151,
	S1ap_ProtocolIE_ID_id_x2TNLConfigurationInfo	= 152,
	S1ap_ProtocolIE_ID_id_eNBX2ExtendedTransportLayerAddresses	= 153,
	S1ap_ProtocolIE_ID_id_GUMMEIList	= 154,
	S1ap_ProtocolIE_ID_id_GW_TransportLayerAddress	= 155,
	S1ap_ProtocolIE_ID_id_Correlation_ID	= 156,
	S1ap_ProtocolIE_ID_id_SourceMME_GUMMEI	= 157,
	S1ap_ProtocolIE_ID_id_MME_UE_S1AP_ID_2	= 158,
	S1ap_ProtocolIE_ID_id_RegisteredLAI	= 159,
	S1ap_ProtocolIE_ID_id_RelayNode_Indicator	= 160,
	S1ap_ProtocolIE_ID_id_TrafficLoadReductionIndication	= 161,
	S1ap_ProtocolIE_ID_id_MDTConfiguration	= 162,
	S1ap_ProtocolIE_ID_id_MMERelaySupportIndicator	= 163,
	S1ap_ProtocolIE_ID_id_GWContextReleaseIndication	= 164,
	S1ap_ProtocolIE_ID_id_ManagementBasedMDTAllowed	= 165,
	S1ap_ProtocolIE_ID_id_PrivacyIndicator	= 166
} e_S1ap_ProtocolIE_ID;

/* S1ap-ProtocolIE-ID */
typedef long	 S1ap_ProtocolIE_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_S1ap_ProtocolIE_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_S1ap_ProtocolIE_ID;
asn_struct_free_f S1ap_ProtocolIE_ID_free;
asn_struct_print_f S1ap_ProtocolIE_ID_print;
asn_constr_check_f S1ap_ProtocolIE_ID_constraint;
ber_type_decoder_f S1ap_ProtocolIE_ID_decode_ber;
der_type_encoder_f S1ap_ProtocolIE_ID_encode_der;
xer_type_decoder_f S1ap_ProtocolIE_ID_decode_xer;
xer_type_encoder_f S1ap_ProtocolIE_ID_encode_xer;
oer_type_decoder_f S1ap_ProtocolIE_ID_decode_oer;
oer_type_encoder_f S1ap_ProtocolIE_ID_encode_oer;
per_type_decoder_f S1ap_ProtocolIE_ID_decode_uper;
per_type_encoder_f S1ap_ProtocolIE_ID_encode_uper;
per_type_decoder_f S1ap_ProtocolIE_ID_decode_aper;
per_type_encoder_f S1ap_ProtocolIE_ID_encode_aper;
#define S1ap_ProtocolIE_ID_id_MME_UE_S1AP_ID	((S1ap_ProtocolIE_ID_t)0)
#define S1ap_ProtocolIE_ID_id_HandoverType	((S1ap_ProtocolIE_ID_t)1)
#define S1ap_ProtocolIE_ID_id_Cause	((S1ap_ProtocolIE_ID_t)2)
#define S1ap_ProtocolIE_ID_id_SourceID	((S1ap_ProtocolIE_ID_t)3)
#define S1ap_ProtocolIE_ID_id_TargetID	((S1ap_ProtocolIE_ID_t)4)
#define S1ap_ProtocolIE_ID_id_eNB_UE_S1AP_ID	((S1ap_ProtocolIE_ID_t)8)
#define S1ap_ProtocolIE_ID_id_E_RABSubjecttoDataForwardingList	((S1ap_ProtocolIE_ID_t)12)
#define S1ap_ProtocolIE_ID_id_E_RABtoReleaseListHOCmd	((S1ap_ProtocolIE_ID_t)13)
#define S1ap_ProtocolIE_ID_id_E_RABDataForwardingItem	((S1ap_ProtocolIE_ID_t)14)
#define S1ap_ProtocolIE_ID_id_E_RABReleaseItemBearerRelComp	((S1ap_ProtocolIE_ID_t)15)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSetupListBearerSUReq	((S1ap_ProtocolIE_ID_t)16)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSetupItemBearerSUReq	((S1ap_ProtocolIE_ID_t)17)
#define S1ap_ProtocolIE_ID_id_E_RABAdmittedList	((S1ap_ProtocolIE_ID_t)18)
#define S1ap_ProtocolIE_ID_id_E_RABFailedToSetupListHOReqAck	((S1ap_ProtocolIE_ID_t)19)
#define S1ap_ProtocolIE_ID_id_E_RABAdmittedItem	((S1ap_ProtocolIE_ID_t)20)
#define S1ap_ProtocolIE_ID_id_E_RABFailedtoSetupItemHOReqAck	((S1ap_ProtocolIE_ID_t)21)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedDLList	((S1ap_ProtocolIE_ID_t)22)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedDLItem	((S1ap_ProtocolIE_ID_t)23)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSetupListCtxtSUReq	((S1ap_ProtocolIE_ID_t)24)
#define S1ap_ProtocolIE_ID_id_TraceActivation	((S1ap_ProtocolIE_ID_t)25)
#define S1ap_ProtocolIE_ID_id_NAS_PDU	((S1ap_ProtocolIE_ID_t)26)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSetupItemHOReq	((S1ap_ProtocolIE_ID_t)27)
#define S1ap_ProtocolIE_ID_id_E_RABSetupListBearerSURes	((S1ap_ProtocolIE_ID_t)28)
#define S1ap_ProtocolIE_ID_id_E_RABFailedToSetupListBearerSURes	((S1ap_ProtocolIE_ID_t)29)
#define S1ap_ProtocolIE_ID_id_E_RABToBeModifiedListBearerModReq	((S1ap_ProtocolIE_ID_t)30)
#define S1ap_ProtocolIE_ID_id_E_RABModifyListBearerModRes	((S1ap_ProtocolIE_ID_t)31)
#define S1ap_ProtocolIE_ID_id_E_RABFailedToModifyList	((S1ap_ProtocolIE_ID_t)32)
#define S1ap_ProtocolIE_ID_id_E_RABToBeReleasedList	((S1ap_ProtocolIE_ID_t)33)
#define S1ap_ProtocolIE_ID_id_E_RABFailedToReleaseList	((S1ap_ProtocolIE_ID_t)34)
#define S1ap_ProtocolIE_ID_id_E_RABItem	((S1ap_ProtocolIE_ID_t)35)
#define S1ap_ProtocolIE_ID_id_E_RABToBeModifiedItemBearerModReq	((S1ap_ProtocolIE_ID_t)36)
#define S1ap_ProtocolIE_ID_id_E_RABModifyItemBearerModRes	((S1ap_ProtocolIE_ID_t)37)
#define S1ap_ProtocolIE_ID_id_E_RABReleaseItem	((S1ap_ProtocolIE_ID_t)38)
#define S1ap_ProtocolIE_ID_id_E_RABSetupItemBearerSURes	((S1ap_ProtocolIE_ID_t)39)
#define S1ap_ProtocolIE_ID_id_SecurityContext	((S1ap_ProtocolIE_ID_t)40)
#define S1ap_ProtocolIE_ID_id_HandoverRestrictionList	((S1ap_ProtocolIE_ID_t)41)
#define S1ap_ProtocolIE_ID_id_UEPagingID	((S1ap_ProtocolIE_ID_t)43)
#define S1ap_ProtocolIE_ID_id_pagingDRX	((S1ap_ProtocolIE_ID_t)44)
#define S1ap_ProtocolIE_ID_id_TAIList	((S1ap_ProtocolIE_ID_t)46)
#define S1ap_ProtocolIE_ID_id_TAIItem	((S1ap_ProtocolIE_ID_t)47)
#define S1ap_ProtocolIE_ID_id_E_RABFailedToSetupListCtxtSURes	((S1ap_ProtocolIE_ID_t)48)
#define S1ap_ProtocolIE_ID_id_E_RABReleaseItemHOCmd	((S1ap_ProtocolIE_ID_t)49)
#define S1ap_ProtocolIE_ID_id_E_RABSetupItemCtxtSURes	((S1ap_ProtocolIE_ID_t)50)
#define S1ap_ProtocolIE_ID_id_E_RABSetupListCtxtSURes	((S1ap_ProtocolIE_ID_t)51)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSetupItemCtxtSUReq	((S1ap_ProtocolIE_ID_t)52)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSetupListHOReq	((S1ap_ProtocolIE_ID_t)53)
#define S1ap_ProtocolIE_ID_id_GERANtoLTEHOInformationRes	((S1ap_ProtocolIE_ID_t)55)
#define S1ap_ProtocolIE_ID_id_UTRANtoLTEHOInformationRes	((S1ap_ProtocolIE_ID_t)57)
#define S1ap_ProtocolIE_ID_id_CriticalityDiagnostics	((S1ap_ProtocolIE_ID_t)58)
#define S1ap_ProtocolIE_ID_id_Global_ENB_ID	((S1ap_ProtocolIE_ID_t)59)
#define S1ap_ProtocolIE_ID_id_eNBname	((S1ap_ProtocolIE_ID_t)60)
#define S1ap_ProtocolIE_ID_id_MMEname	((S1ap_ProtocolIE_ID_t)61)
#define S1ap_ProtocolIE_ID_id_ServedPLMNs	((S1ap_ProtocolIE_ID_t)63)
#define S1ap_ProtocolIE_ID_id_SupportedTAs	((S1ap_ProtocolIE_ID_t)64)
#define S1ap_ProtocolIE_ID_id_TimeToWait	((S1ap_ProtocolIE_ID_t)65)
#define S1ap_ProtocolIE_ID_id_uEaggregateMaximumBitrate	((S1ap_ProtocolIE_ID_t)66)
#define S1ap_ProtocolIE_ID_id_TAI	((S1ap_ProtocolIE_ID_t)67)
#define S1ap_ProtocolIE_ID_id_E_RABReleaseListBearerRelComp	((S1ap_ProtocolIE_ID_t)69)
#define S1ap_ProtocolIE_ID_id_cdma2000PDU	((S1ap_ProtocolIE_ID_t)70)
#define S1ap_ProtocolIE_ID_id_cdma2000RATType	((S1ap_ProtocolIE_ID_t)71)
#define S1ap_ProtocolIE_ID_id_cdma2000SectorID	((S1ap_ProtocolIE_ID_t)72)
#define S1ap_ProtocolIE_ID_id_SecurityKey	((S1ap_ProtocolIE_ID_t)73)
#define S1ap_ProtocolIE_ID_id_UERadioCapability	((S1ap_ProtocolIE_ID_t)74)
#define S1ap_ProtocolIE_ID_id_GUMMEI_ID	((S1ap_ProtocolIE_ID_t)75)
#define S1ap_ProtocolIE_ID_id_E_RABInformationListItem	((S1ap_ProtocolIE_ID_t)78)
#define S1ap_ProtocolIE_ID_id_Direct_Forwarding_Path_Availability	((S1ap_ProtocolIE_ID_t)79)
#define S1ap_ProtocolIE_ID_id_UEIdentityIndexValue	((S1ap_ProtocolIE_ID_t)80)
#define S1ap_ProtocolIE_ID_id_cdma2000HOStatus	((S1ap_ProtocolIE_ID_t)83)
#define S1ap_ProtocolIE_ID_id_cdma2000HORequiredIndication	((S1ap_ProtocolIE_ID_t)84)
#define S1ap_ProtocolIE_ID_id_E_UTRAN_Trace_ID	((S1ap_ProtocolIE_ID_t)86)
#define S1ap_ProtocolIE_ID_id_RelativeMMECapacity	((S1ap_ProtocolIE_ID_t)87)
#define S1ap_ProtocolIE_ID_id_SourceMME_UE_S1AP_ID	((S1ap_ProtocolIE_ID_t)88)
#define S1ap_ProtocolIE_ID_id_Bearers_SubjectToStatusTransfer_Item	((S1ap_ProtocolIE_ID_t)89)
#define S1ap_ProtocolIE_ID_id_eNB_StatusTransfer_TransparentContainer	((S1ap_ProtocolIE_ID_t)90)
#define S1ap_ProtocolIE_ID_id_UE_associatedLogicalS1_ConnectionItem	((S1ap_ProtocolIE_ID_t)91)
#define S1ap_ProtocolIE_ID_id_ResetType	((S1ap_ProtocolIE_ID_t)92)
#define S1ap_ProtocolIE_ID_id_UE_associatedLogicalS1_ConnectionListResAck	((S1ap_ProtocolIE_ID_t)93)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedULItem	((S1ap_ProtocolIE_ID_t)94)
#define S1ap_ProtocolIE_ID_id_E_RABToBeSwitchedULList	((S1ap_ProtocolIE_ID_t)95)
#define S1ap_ProtocolIE_ID_id_S_TMSI	((S1ap_ProtocolIE_ID_t)96)
#define S1ap_ProtocolIE_ID_id_cdma2000OneXRAND	((S1ap_ProtocolIE_ID_t)97)
#define S1ap_ProtocolIE_ID_id_RequestType	((S1ap_ProtocolIE_ID_t)98)
#define S1ap_ProtocolIE_ID_id_UE_S1AP_IDs	((S1ap_ProtocolIE_ID_t)99)
#define S1ap_ProtocolIE_ID_id_EUTRAN_CGI	((S1ap_ProtocolIE_ID_t)100)
#define S1ap_ProtocolIE_ID_id_OverloadResponse	((S1ap_ProtocolIE_ID_t)101)
#define S1ap_ProtocolIE_ID_id_cdma2000OneXSRVCCInfo	((S1ap_ProtocolIE_ID_t)102)
#define S1ap_ProtocolIE_ID_id_E_RABFailedToBeReleasedList	((S1ap_ProtocolIE_ID_t)103)
#define S1ap_ProtocolIE_ID_id_Source_ToTarget_TransparentContainer	((S1ap_ProtocolIE_ID_t)104)
#define S1ap_ProtocolIE_ID_id_ServedGUMMEIs	((S1ap_ProtocolIE_ID_t)105)
#define S1ap_ProtocolIE_ID_id_SubscriberProfileIDforRFP	((S1ap_ProtocolIE_ID_t)106)
#define S1ap_ProtocolIE_ID_id_UESecurityCapabilities	((S1ap_ProtocolIE_ID_t)107)
#define S1ap_ProtocolIE_ID_id_CSFallbackIndicator	((S1ap_ProtocolIE_ID_t)108)
#define S1ap_ProtocolIE_ID_id_CNDomain	((S1ap_ProtocolIE_ID_t)109)
#define S1ap_ProtocolIE_ID_id_E_RABReleasedList	((S1ap_ProtocolIE_ID_t)110)
#define S1ap_ProtocolIE_ID_id_MessageIdentifier	((S1ap_ProtocolIE_ID_t)111)
#define S1ap_ProtocolIE_ID_id_SerialNumber	((S1ap_ProtocolIE_ID_t)112)
#define S1ap_ProtocolIE_ID_id_WarningAreaList	((S1ap_ProtocolIE_ID_t)113)
#define S1ap_ProtocolIE_ID_id_RepetitionPeriod	((S1ap_ProtocolIE_ID_t)114)
#define S1ap_ProtocolIE_ID_id_NumberofBroadcastRequest	((S1ap_ProtocolIE_ID_t)115)
#define S1ap_ProtocolIE_ID_id_WarningType	((S1ap_ProtocolIE_ID_t)116)
#define S1ap_ProtocolIE_ID_id_WarningSecurityInfo	((S1ap_ProtocolIE_ID_t)117)
#define S1ap_ProtocolIE_ID_id_DataCodingScheme	((S1ap_ProtocolIE_ID_t)118)
#define S1ap_ProtocolIE_ID_id_WarningMessageContents	((S1ap_ProtocolIE_ID_t)119)
#define S1ap_ProtocolIE_ID_id_BroadcastCompletedAreaList	((S1ap_ProtocolIE_ID_t)120)
#define S1ap_ProtocolIE_ID_id_Inter_SystemInformationTransferTypeEDT	((S1ap_ProtocolIE_ID_t)121)
#define S1ap_ProtocolIE_ID_id_Inter_SystemInformationTransferTypeMDT	((S1ap_ProtocolIE_ID_t)122)
#define S1ap_ProtocolIE_ID_id_Target_ToSource_TransparentContainer	((S1ap_ProtocolIE_ID_t)123)
#define S1ap_ProtocolIE_ID_id_SRVCCOperationPossible	((S1ap_ProtocolIE_ID_t)124)
#define S1ap_ProtocolIE_ID_id_SRVCCHOIndication	((S1ap_ProtocolIE_ID_t)125)
#define S1ap_ProtocolIE_ID_id_NAS_DownlinkCount	((S1ap_ProtocolIE_ID_t)126)
#define S1ap_ProtocolIE_ID_id_CSG_Id	((S1ap_ProtocolIE_ID_t)127)
#define S1ap_ProtocolIE_ID_id_CSG_IdList	((S1ap_ProtocolIE_ID_t)128)
#define S1ap_ProtocolIE_ID_id_SONConfigurationTransferECT	((S1ap_ProtocolIE_ID_t)129)
#define S1ap_ProtocolIE_ID_id_SONConfigurationTransferMCT	((S1ap_ProtocolIE_ID_t)130)
#define S1ap_ProtocolIE_ID_id_TraceCollectionEntityIPAddress	((S1ap_ProtocolIE_ID_t)131)
#define S1ap_ProtocolIE_ID_id_MSClassmark2	((S1ap_ProtocolIE_ID_t)132)
#define S1ap_ProtocolIE_ID_id_MSClassmark3	((S1ap_ProtocolIE_ID_t)133)
#define S1ap_ProtocolIE_ID_id_RRC_Establishment_Cause	((S1ap_ProtocolIE_ID_t)134)
#define S1ap_ProtocolIE_ID_id_NASSecurityParametersfromE_UTRAN	((S1ap_ProtocolIE_ID_t)135)
#define S1ap_ProtocolIE_ID_id_NASSecurityParameterstoE_UTRAN	((S1ap_ProtocolIE_ID_t)136)
#define S1ap_ProtocolIE_ID_id_DefaultPagingDRX	((S1ap_ProtocolIE_ID_t)137)
#define S1ap_ProtocolIE_ID_id_Source_ToTarget_TransparentContainer_Secondary	((S1ap_ProtocolIE_ID_t)138)
#define S1ap_ProtocolIE_ID_id_Target_ToSource_TransparentContainer_Secondary	((S1ap_ProtocolIE_ID_t)139)
#define S1ap_ProtocolIE_ID_id_EUTRANRoundTripDelayEstimationInfo	((S1ap_ProtocolIE_ID_t)140)
#define S1ap_ProtocolIE_ID_id_BroadcastCancelledAreaList	((S1ap_ProtocolIE_ID_t)141)
#define S1ap_ProtocolIE_ID_id_ConcurrentWarningMessageIndicator	((S1ap_ProtocolIE_ID_t)142)
#define S1ap_ProtocolIE_ID_id_Data_Forwarding_Not_Possible	((S1ap_ProtocolIE_ID_t)143)
#define S1ap_ProtocolIE_ID_id_ExtendedRepetitionPeriod	((S1ap_ProtocolIE_ID_t)144)
#define S1ap_ProtocolIE_ID_id_CellAccessMode	((S1ap_ProtocolIE_ID_t)145)
#define S1ap_ProtocolIE_ID_id_CSGMembershipStatus	((S1ap_ProtocolIE_ID_t)146)
#define S1ap_ProtocolIE_ID_id_LPPa_PDU	((S1ap_ProtocolIE_ID_t)147)
#define S1ap_ProtocolIE_ID_id_Routing_ID	((S1ap_ProtocolIE_ID_t)148)
#define S1ap_ProtocolIE_ID_id_Time_Synchronization_Info	((S1ap_ProtocolIE_ID_t)149)
#define S1ap_ProtocolIE_ID_id_PS_ServiceNotAvailable	((S1ap_ProtocolIE_ID_t)150)
#define S1ap_ProtocolIE_ID_id_PagingPriority	((S1ap_ProtocolIE_ID_t)151)
#define S1ap_ProtocolIE_ID_id_x2TNLConfigurationInfo	((S1ap_ProtocolIE_ID_t)152)
#define S1ap_ProtocolIE_ID_id_eNBX2ExtendedTransportLayerAddresses	((S1ap_ProtocolIE_ID_t)153)
#define S1ap_ProtocolIE_ID_id_GUMMEIList	((S1ap_ProtocolIE_ID_t)154)
#define S1ap_ProtocolIE_ID_id_GW_TransportLayerAddress	((S1ap_ProtocolIE_ID_t)155)
#define S1ap_ProtocolIE_ID_id_Correlation_ID	((S1ap_ProtocolIE_ID_t)156)
#define S1ap_ProtocolIE_ID_id_SourceMME_GUMMEI	((S1ap_ProtocolIE_ID_t)157)
#define S1ap_ProtocolIE_ID_id_MME_UE_S1AP_ID_2	((S1ap_ProtocolIE_ID_t)158)
#define S1ap_ProtocolIE_ID_id_RegisteredLAI	((S1ap_ProtocolIE_ID_t)159)
#define S1ap_ProtocolIE_ID_id_RelayNode_Indicator	((S1ap_ProtocolIE_ID_t)160)
#define S1ap_ProtocolIE_ID_id_TrafficLoadReductionIndication	((S1ap_ProtocolIE_ID_t)161)
#define S1ap_ProtocolIE_ID_id_MDTConfiguration	((S1ap_ProtocolIE_ID_t)162)
#define S1ap_ProtocolIE_ID_id_MMERelaySupportIndicator	((S1ap_ProtocolIE_ID_t)163)
#define S1ap_ProtocolIE_ID_id_GWContextReleaseIndication	((S1ap_ProtocolIE_ID_t)164)
#define S1ap_ProtocolIE_ID_id_ManagementBasedMDTAllowed	((S1ap_ProtocolIE_ID_t)165)
#define S1ap_ProtocolIE_ID_id_PrivacyIndicator	((S1ap_ProtocolIE_ID_t)166)

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_ProtocolIE_ID_H_ */
#include <asn_internal.h>
