/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU"
 * 	found in "./support/s1ap-r10.5.0/S1AP-PDU.asn"
 * 	`asn1c -D ./common -gen-PER -pdu=all -fcompound-names -fno-include-deps -no-gen-example`
 */

#ifndef	_S1ap_InitiatingMessage_H_
#define	_S1ap_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1ap-ProcedureCode.h"
#include "S1ap-Criticality.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S1ap-InitiatingMessage */
typedef struct S1ap_InitiatingMessage {
	S1ap_ProcedureCode_t	 procedureCode;
	S1ap_Criticality_t	 criticality;
	ANY_t	 value;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_S1ap_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_InitiatingMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_InitiatingMessage_H_ */
#include <asn_internal.h>
